#!/usr/bin/env bash
# bootstrap_tests.sh — fast-fail subset generated by smart-tests-bootstrap
# Codebase snapshot: 2026-07-19 | Total tests: ~3373 | Selected: ~850 (~25%)
# Expensive Nova TestCS/setup/proof gates are unconditionally milestone-only.
# The ordinary packet retains one canonical+mutation full-R1CS smoke plus
# source/dependency/owner/coverage guards and reports the exact tier contract.
# Physical path: ./.github/skills/smart-tests-bootstrap/scripts/bootstrap_tests.sh
set -euo pipefail

THREADS="${BOOTSTRAP_THREADS:-4}"
NOVA_VERIFICATION="./.github/skills/smart-tests-bootstrap/scripts/nova_milestone_tests.sh"
WALLET_FEATURES="z00z_wallets/claim-auth-sign,z00z_wallets/ownership_policy_keyring"

echo "=== foundational units ==="
"$NOVA_VERIFICATION" guards
cargo test --release --lib \
  -p z00z_crypto \
  -p z00z_core \
  -p z00z_storage \
  -p z00z_utils \
  --features "$WALLET_FEATURES" \
  -- --test-threads "$THREADS"
cargo test --release -p z00z_storage \
  --features "$WALLET_FEATURES" \
  --test test_recursive_v2_nova_step \
  --test test_recursive_v2_nova_adversarial \
  -- --nocapture --test-threads "$THREADS"
echo "Nova curated release packet: PASS (source/dependency units + one canonical/mutation R1CS smoke + 2 integration targets)"

echo "=== wallet integration ==="
cargo test -p z00z_wallets --release --features claim-auth-sign,ownership_policy_keyring \
  --test test_tx_stealth_flow \
  --test test_tx_tamper \
  --test test_tx_fee \
  --test test_tx_roundtrip \
  --test test_tx_poison \
  --test test_tx_balance \
  --test test_golden_vectors \
  --test test_golden_tag16 \
  --test test_golden_recv_keys \
  --test test_golden_owner_tag \
  --test test_manager \
  --test test_manager_storage_unlock \
  --test test_ecdh \
  --test test_kdf \
  --test test_adversarial \
  --test test_claim_core_safety \
  --test test_claim_import_reason_codes \
  --test test_claim_resume_core \
  --test test_claim_state_compat \
  --test test_claim_state_core \
  --test test_asset_replay_protection \
  --test test_asset_ownership_security \
  -- --test-threads "$THREADS"

echo "=== compile checks ==="
echo "deferred: benches/examples are required in the post-bootstrap broad release gate"

echo "=== BOOTSTRAP COMPLETE ==="
