#!/usr/bin/env bash
set -uo pipefail

scope="${1:-.}"

have() {
  command -v "$1" >/dev/null 2>&1
}

print_section() {
  printf '\n## %s\n\n' "$1"
}

repo_root() {
  if have git; then
    git rev-parse --show-toplevel 2>/dev/null || pwd
  else
    pwd
  fi
}

list_files() {
  local pattern="$1"
  if have rg; then
    rg --files "$scope" -g "$pattern" 2>/dev/null
  else
    find "$scope" -type f -name "$pattern" 2>/dev/null
  fi
}

line_search() {
  local pattern="$1"
  if have rg; then
    rg -n "$pattern" "$scope" 2>/dev/null
  else
    grep -RInE "$pattern" "$scope" 2>/dev/null
  fi
}

root="$(repo_root)"

printf '# Rust Attack Surface Inventory\n\n'
printf -- '- Scope: `%s`\n' "$scope"
printf -- '- Repository root: `%s`\n' "$root"
printf -- '- Generated by: `rust_inventory.sh`\n'

print_section "Tool Availability"
for tool in rg cargo rustc rustdoc rust-analyzer cargo-geiger cargo-audit cargo-deny cargo-nextest cargo-llvm-cov; do
  if have "$tool"; then
    printf -- '- `%s`: available\n' "$tool"
  else
    printf -- '- `%s`: missing\n' "$tool"
  fi
done

print_section "Cargo Manifests"
manifests="$(list_files Cargo.toml)"
if [ -n "$manifests" ]; then
  printf '%s\n' "$manifests" | sed 's/^/- /'
else
  printf -- '- No Cargo.toml files found in scope.\n'
fi

print_section "Workspace Metadata"
if have cargo && [ -f Cargo.toml ]; then
  metadata_json="$(cargo metadata --format-version 1 --no-deps 2>/dev/null || true)"
  if [ -n "$metadata_json" ] && have python3; then
    printf '%s' "$metadata_json" | python3 -c '
import json
import sys

data = json.load(sys.stdin)
workspace_ids = set(data.get("workspace_members", []))
packages = data.get("packages", [])
workspace = [pkg for pkg in packages if pkg.get("id") in workspace_ids]

def lane_for(name, manifest):
    text = f"{name} {manifest}".lower()
    if "z00z_core" in text:
        return "core protocol/state"
    if "z00z_crypto" in text or "/tari/" in text:
        return "crypto/proof/facade"
    if "wallet" in text:
        return "wallet/secrets/rpc/persistence"
    if "storage" in text:
        return "storage/checkpoint/settlement"
    if "rollup" in text:
        return "rollup/settlement/node-rpc"
    if "aggregator" in text or "validator" in text or "watcher" in text:
        return "runtime/validator/watcher"
    if "network" in text or "onion" in text or "rpc" in text:
        return "network/rpc/transport"
    if "utils" in text:
        return "utils/abstractions"
    if "simulator" in text or "telemetry" in text or "extension" in text:
        return "support/simulator/telemetry"
    return "unclassified"

print(f"- Workspace packages: {len(workspace)}")
print("")
print("| Package | Version | Manifest | Architecture Lane |")
print("| --- | --- | --- | --- |")
for pkg in sorted(workspace, key=lambda item: item.get("name", "")):
    manifest = pkg.get("manifest_path", "")
    name = pkg.get("name", "")
    version = pkg.get("version", "")
    lane = lane_for(name, manifest)
    print(f"| {name} | {version} | `{manifest}` | {lane} |")
'
  elif [ -n "$metadata_json" ]; then
    printf '%s\n' "$metadata_json"
  else
    printf 'cargo metadata failed for this scope.\n'
  fi
else
  printf 'cargo metadata skipped: cargo missing or current directory has no Cargo.toml.\n'
fi

print_section "Dependency Tree"
if have cargo && [ -f Cargo.toml ]; then
  dep_tree="$(
    cargo tree --workspace --all-features --depth 2 --prefix depth 2>/dev/null \
      || cargo tree --workspace --depth 2 --prefix depth 2>/dev/null \
      || true
  )"
  if [ -n "$dep_tree" ]; then
    dep_count="$(printf '%s\n' "$dep_tree" | wc -l | tr -d ' ')"
    printf -- '- Dependency tree line count: `%s`\n\n' "$dep_count"
    printf '%s\n' "$dep_tree" | head -300
    if [ "$dep_count" -gt 300 ]; then
      printf '\nDependency tree truncated after 300 lines. Re-run `cargo tree --workspace --all-features --depth 2` for the full tree.\n'
    fi
  else
    printf 'cargo tree failed for this scope.\n'
  fi
else
  printf 'cargo tree skipped: cargo missing or current directory has no Cargo.toml.\n'
fi

print_section "Rust Source Files"
rs_files="$(list_files '*.rs')"
if [ -n "$rs_files" ]; then
  rs_count="$(printf '%s\n' "$rs_files" | sed '/^$/d' | wc -l | tr -d ' ')"
  printf -- '- Rust source file count: `%s`\n' "$rs_count"
  printf '%s\n' "$rs_files" | sed '/^$/d' | head -250 | sed 's/^/- /'
  if [ "$rs_count" -gt 250 ]; then
    printf -- '- Output truncated after 250 Rust source files. Use `rg --files <scope> -g "*.rs"` for the full list.\n'
  fi
else
  printf -- '- No Rust source files found in scope.\n'
fi

print_section "Build, Test, Bench, Fuzz, And Example Surfaces"
for pattern in build.rs '*.yml' '*.yaml'; do
  files="$(list_files "$pattern")"
  if [ -n "$files" ]; then
    printf '### `%s`\n\n' "$pattern"
    printf '%s\n\n' "$files" | sed 's/^/- /'
  fi
done

for dir in examples tests benches fuzz .github/workflows; do
  if [ -d "$scope/$dir" ]; then
    printf -- '- `%s/%s`\n' "$scope" "$dir"
  fi
done

print_section "Feature Flag Hints"
feature_lines=""
if [ -n "$manifests" ]; then
  while IFS= read -r manifest; do
    if have rg; then
      feature_lines="${feature_lines}$(rg -nH '^\s*\[features\]|^\s*[A-Za-z0-9_-]+\s*=\s*\[' "$manifest" 2>/dev/null)
"
    else
      feature_lines="${feature_lines}$(grep -InE '^\s*\[features\]|^\s*[A-Za-z0-9_-]+\s*=\s*\[' "$manifest" 2>/dev/null)
"
    fi
  done <<< "$manifests"
fi
if [ -n "$feature_lines" ]; then
  printf '%s\n' "$feature_lines"
else
  printf 'No feature declarations found by text scan.\n'
fi

print_section "Security-Relevant Text Hotspots"
hotspots="$(line_search '\b(unsafe|unwrap\(|expect\(|panic!|todo!|unimplemented!|deserialize|serialize|from_bytes|to_bytes|verify|validate|nonce|random|rng|secret|key|proof|commit|signature|nullifier|transcript|auth|permission|capability|Mutex|RwLock|Atomic|spawn|unsafe impl|extern "C"|static mut)\b' || true)"
if [ -n "$hotspots" ]; then
  hotspot_count="$(printf '%s\n' "$hotspots" | wc -l | tr -d ' ')"
  printf -- '- Hotspot match count: `%s`\n\n' "$hotspot_count"
  printf '%s\n' "$hotspots" | head -250
  if [ "$hotspot_count" -gt 250 ]; then
    printf '\nOutput truncated after 250 hotspot lines. Re-run targeted `rg` searches per architecture lane.\n'
  fi
else
  printf 'No security-relevant text hotspots found by broad scan.\n'
fi
