"use strict";

(() => {
  const i18n = window.Z00ZI18n;
  if (!i18n?.extendLocale) throw new Error("Z00Z navigation labels must load after the locale catalogues.");

  // These labels are intentionally separate from the navigation model: the
  // model owns stable IDs, while every renderer receives localised copy.
  const english = Object.freeze({
    wallet: "Wallet", overview: "Overview", assets: "Assets", vouchers: "Vouchers", permissions: "Permissions", quarantine: "Quarantine", send: "Send", receive: "Receive", import: "Import", mergeSplit: "Merge/Split", history: "History", swap: "Swap", earn: "Earn", stake: "Stake", unstake: "Unstake", backup: "Backup", walletSettings: "Wallet Settings", general: "General", security: "Security", policies: "Policies", advanced: "Advanced",
    telemetry: "Telemetry", telemetryContext: "Read-only local observation and publication evidence", network: "Network", reticulum: "Reticulum", onionnet: "OnionNet", quic: "QUIC", aggregators: "Aggregators", node: "Node", interfaces: "Interfaces", radio: "Radio", entrypoints: "Entrypoints", paths: "Paths", probes: "Probes", links: "Links", epoch: "Epoch", privacy: "Privacy", transport: "Transport", queues: "Queues", probation: "Probation", ingress: "Ingress", planning: "Planning", placement: "Placement", publication: "Publication", recovery: "Recovery", watchers: "Watchers", alerts: "Alerts", publicationChecks: "Publication checks", daProviders: "DA providers", censorship: "Censorship signals", evidenceExport: "Evidence export", explorer: "Explorer", search: "Search", checkpoints: "Checkpoints", batches: "Batches", publicEvidence: "Public evidence",
    dapps: "dApps", discover: "Discover dApps", pay: "Pay", request: "Request", createAsset: "Create Asset", createVoucher: "Create Voucher", createPermission: "Create Permission", agentsBudget: "Agent Budget", wboldGateway: "wCoins Gateway", xchainIntegration: "X-Chain Integration", subscription: "Subscription", donation: "Donation", escrow: "Escrow", bounties: "Bounty", ticketsPasses: "Ticket & Pass", serviceCredits: "Service Credit", digitalGoods: "Digital Goods", payroll: "Payroll", privateContract: "Private Agreement", assetsLocker: "Assets Locker", activity: "Activity", messenger: "Messenger", inbox: "Inbox", sent: "Sent", requests: "Requests", conversations: "Conversations", outbox: "Outbox", receipts: "Receipts", contacts: "Contacts", dataStorage: "Data & Storage", diskUsage: "Disk Usage", networkUsage: "Network Usage", settings: "Settings", notifications: "Notifications", appearance: "Appearance", help: "Help", about: "About", logOut: "Log out", roadmap: "Roadmap"
  });

  const translations = Object.freeze({
    ru: { wallet: "Кошелёк", overview: "Обзор", assets: "Активы", vouchers: "Ваучеры", permissions: "Полномочия", quarantine: "Карантин", send: "Отправить", receive: "Получить", history: "История", backup: "Резервная копия", walletSettings: "Настройки кошелька", general: "Общие", security: "Безопасность", policies: "Политики", advanced: "Расширенные", telemetry: "Телеметрия", interfaces: "Интерфейсы", entrypoints: "Точки входа", paths: "Маршруты", probes: "Проверки", links: "Связи", privacy: "Приватность", transport: "Транспорт", queues: "Очереди", ingress: "Вход", planning: "Планирование", placement: "Размещение", publication: "Публикация", recovery: "Восстановление", watchers: "Наблюдатели", alerts: "Оповещения", publicationChecks: "Проверки публикации", daProviders: "DA-провайдеры", censorship: "Сигналы цензуры", evidenceExport: "Экспорт доказательств", explorer: "Обозреватель", search: "Поиск", checkpoints: "Контрольные точки", batches: "Пакеты", publicEvidence: "Публичные доказательства", discover: "Найти dApps", connections: "Подключения", activity: "Активность", messenger: "Мессенджер", inbox: "Входящие", sent: "Отправленные", requests: "Запросы", conversations: "Диалоги", outbox: "Исходящие", receipts: "Квитанции", contacts: "Контакты", settings: "Настройки", appearance: "Оформление", help: "Справка", logOut: "Выйти", roadmap: "План развития" },
    fr: { wallet: "Portefeuille", overview: "Aperçu", assets: "Actifs", vouchers: "Bons", permissions: "Autorisations", quarantine: "Quarantaine", send: "Envoyer", receive: "Recevoir", history: "Historique", backup: "Sauvegarde", walletSettings: "Réglages du portefeuille", general: "Général", security: "Sécurité", policies: "Politiques", advanced: "Avancé", telemetry: "Télémétrie", interfaces: "Interfaces", entrypoints: "Points d'entrée", paths: "Chemins", probes: "Sondes", links: "Liens", privacy: "Confidentialité", transport: "Transport", queues: "Files", ingress: "Entrée", planning: "Planification", placement: "Placement", publication: "Publication", recovery: "Récupération", watchers: "Observateurs", alerts: "Alertes", publicationChecks: "Vérifications de publication", daProviders: "Fournisseurs DA", censorship: "Signaux de censure", evidenceExport: "Export de preuves", explorer: "Explorateur", search: "Rechercher", checkpoints: "Points de contrôle", batches: "Lots", publicEvidence: "Preuves publiques", discover: "Découvrir les dApps", connections: "Connexions", activity: "Activité", messenger: "Messagerie", inbox: "Boîte de réception", sent: "Envoyés", requests: "Demandes", conversations: "Conversations", outbox: "Boîte d'envoi", receipts: "Reçus", contacts: "Contacts", settings: "Réglages", appearance: "Apparence", help: "Aide", logOut: "Déconnexion", roadmap: "Feuille de route" },
    de: { wallet: "Wallet", overview: "Übersicht", assets: "Vermögen", vouchers: "Gutscheine", permissions: "Berechtigungen", quarantine: "Quarantäne", send: "Senden", receive: "Empfangen", history: "Verlauf", backup: "Sicherung", walletSettings: "Wallet-Einstellungen", general: "Allgemein", security: "Sicherheit", policies: "Richtlinien", advanced: "Erweitert", telemetry: "Telemetrie", interfaces: "Schnittstellen", entrypoints: "Einstiegspunkte", paths: "Pfade", probes: "Sonden", links: "Verbindungen", privacy: "Privatsphäre", transport: "Transport", queues: "Warteschlangen", ingress: "Eingang", planning: "Planung", placement: "Platzierung", publication: "Veröffentlichung", recovery: "Wiederherstellung", watchers: "Beobachter", alerts: "Warnungen", publicationChecks: "Publikationsprüfungen", daProviders: "DA-Anbieter", censorship: "Zensursignale", evidenceExport: "Beweisexport", explorer: "Explorer", search: "Suchen", checkpoints: "Prüfpunkte", batches: "Stapel", publicEvidence: "Öffentliche Beweise", discover: "dApps entdecken", connections: "Verbindungen", activity: "Aktivität", messenger: "Messenger", inbox: "Posteingang", sent: "Gesendet", requests: "Anfragen", conversations: "Unterhaltungen", outbox: "Postausgang", receipts: "Belege", contacts: "Kontakte", settings: "Einstellungen", appearance: "Darstellung", help: "Hilfe", logOut: "Abmelden", roadmap: "Roadmap" },
    es: { wallet: "Cartera", overview: "Resumen", assets: "Activos", vouchers: "Vales", permissions: "Permisos", quarantine: "Cuarentena", send: "Enviar", receive: "Recibir", history: "Historial", backup: "Copia de seguridad", walletSettings: "Ajustes de cartera", general: "General", security: "Seguridad", policies: "Políticas", advanced: "Avanzado", telemetry: "Telemetría", interfaces: "Interfaces", entrypoints: "Puntos de entrada", paths: "Rutas", probes: "Sondas", links: "Enlaces", privacy: "Privacidad", transport: "Transporte", queues: "Colas", ingress: "Entrada", planning: "Planificación", placement: "Ubicación", publication: "Publicación", recovery: "Recuperación", watchers: "Observadores", alerts: "Alertas", publicationChecks: "Comprobaciones de publicación", daProviders: "Proveedores DA", censorship: "Señales de censura", evidenceExport: "Exportar pruebas", explorer: "Explorador", search: "Buscar", checkpoints: "Puntos de control", batches: "Lotes", publicEvidence: "Pruebas públicas", discover: "Descubrir dApps", connections: "Conexiones", activity: "Actividad", messenger: "Mensajero", inbox: "Bandeja de entrada", sent: "Enviados", requests: "Solicitudes", conversations: "Conversaciones", outbox: "Bandeja de salida", receipts: "Recibos", contacts: "Contactos", settings: "Ajustes", appearance: "Apariencia", help: "Ayuda", logOut: "Cerrar sesión", roadmap: "Hoja de ruta" },
    pt: { wallet: "Carteira", overview: "Visão geral", assets: "Ativos", vouchers: "Vales", permissions: "Permissões", quarantine: "Quarentena", send: "Enviar", receive: "Receber", history: "Histórico", backup: "Cópia de segurança", walletSettings: "Definições da carteira", general: "Geral", security: "Segurança", policies: "Políticas", advanced: "Avançado", telemetry: "Telemetria", interfaces: "Interfaces", entrypoints: "Pontos de entrada", paths: "Caminhos", probes: "Sondas", links: "Ligações", privacy: "Privacidade", transport: "Transporte", queues: "Filas", ingress: "Entrada", planning: "Planeamento", placement: "Posicionamento", publication: "Publicação", recovery: "Recuperação", watchers: "Observadores", alerts: "Alertas", publicationChecks: "Verificações de publicação", daProviders: "Fornecedores DA", censorship: "Sinais de censura", evidenceExport: "Exportar evidências", explorer: "Explorador", search: "Pesquisar", checkpoints: "Pontos de controlo", batches: "Lotes", publicEvidence: "Evidência pública", discover: "Descobrir dApps", connections: "Ligações", activity: "Atividade", messenger: "Mensageiro", inbox: "Caixa de entrada", sent: "Enviados", requests: "Pedidos", conversations: "Conversas", outbox: "Caixa de saída", receipts: "Recibos", contacts: "Contactos", settings: "Definições", appearance: "Aparência", help: "Ajuda", logOut: "Terminar sessão", roadmap: "Roteiro" },
    ko: { wallet: "지갑", overview: "개요", assets: "자산", vouchers: "바우처", permissions: "권한", quarantine: "격리", send: "보내기", receive: "받기", history: "기록", backup: "백업", walletSettings: "지갑 설정", general: "일반", security: "보안", policies: "정책", advanced: "고급", telemetry: "텔레메트리", interfaces: "인터페이스", entrypoints: "진입점", paths: "경로", probes: "프로브", links: "링크", privacy: "개인정보", transport: "전송", queues: "대기열", ingress: "수신", planning: "계획", placement: "배치", publication: "게시", recovery: "복구", watchers: "감시자", alerts: "알림", publicationChecks: "게시 확인", daProviders: "DA 제공자", censorship: "검열 신호", evidenceExport: "증거 내보내기", explorer: "탐색기", search: "검색", checkpoints: "검사점", batches: "배치", publicEvidence: "공개 증거", discover: "dApps 찾아보기", connections: "연결", activity: "활동", messenger: "메신저", inbox: "받은편지함", sent: "보낸편지함", requests: "요청", conversations: "대화", outbox: "보낸편지함", receipts: "영수증", contacts: "연락처", settings: "설정", appearance: "모양", help: "도움말", logOut: "로그아웃", roadmap: "로드맵" },
    tr: { wallet: "Cüzdan", overview: "Genel bakış", assets: "Varlıklar", vouchers: "Kuponlar", permissions: "İzinler", quarantine: "Karantina", send: "Gönder", receive: "Al", history: "Geçmiş", backup: "Yedek", walletSettings: "Cüzdan ayarları", general: "Genel", security: "Güvenlik", policies: "İlkeler", advanced: "Gelişmiş", telemetry: "Telemetri", interfaces: "Arayüzler", entrypoints: "Giriş noktaları", paths: "Yollar", probes: "Sondalar", links: "Bağlantılar", privacy: "Gizlilik", transport: "Aktarım", queues: "Kuyruklar", ingress: "Giriş", planning: "Planlama", placement: "Yerleştirme", publication: "Yayınlama", recovery: "Kurtarma", watchers: "İzleyiciler", alerts: "Uyarılar", publicationChecks: "Yayın kontrolleri", daProviders: "DA sağlayıcıları", censorship: "Sansür sinyalleri", evidenceExport: "Kanıt dışa aktarma", explorer: "Gezgin", search: "Ara", checkpoints: "Kontrol noktaları", batches: "Partiler", publicEvidence: "Genel kanıt", discover: "dApps keşfet", connections: "Bağlantılar", activity: "Etkinlik", messenger: "Mesajlaşma", inbox: "Gelen kutusu", sent: "Gönderilenler", requests: "İstekler", conversations: "Konuşmalar", outbox: "Giden kutusu", receipts: "Makbuzlar", contacts: "Kişiler", settings: "Ayarlar", appearance: "Görünüm", help: "Yardım", logOut: "Çıkış", roadmap: "Yol haritası" },
    ja: { wallet: "ウォレット", overview: "概要", assets: "資産", vouchers: "バウチャー", permissions: "権限", quarantine: "隔離", send: "送信", receive: "受信", history: "履歴", backup: "バックアップ", walletSettings: "ウォレット設定", general: "一般", security: "セキュリティ", policies: "ポリシー", advanced: "詳細", telemetry: "テレメトリー", interfaces: "インターフェース", entrypoints: "エントリーポイント", paths: "経路", probes: "プローブ", links: "リンク", privacy: "プライバシー", transport: "転送", queues: "キュー", ingress: "受信", planning: "計画", placement: "配置", publication: "公開", recovery: "復旧", watchers: "監視", alerts: "アラート", publicationChecks: "公開確認", daProviders: "DAプロバイダー", censorship: "検閲シグナル", evidenceExport: "証拠をエクスポート", explorer: "エクスプローラー", search: "検索", checkpoints: "チェックポイント", batches: "バッチ", publicEvidence: "公開証拠", discover: "dApps を探す", connections: "接続", activity: "アクティビティ", messenger: "メッセンジャー", inbox: "受信トレイ", sent: "送信済み", requests: "リクエスト", conversations: "会話", outbox: "送信トレイ", receipts: "受領書", contacts: "連絡先", settings: "設定", appearance: "外観", help: "ヘルプ", logOut: "ログアウト", roadmap: "ロードマップ" },
    "zh-Hans": { wallet: "钱包", overview: "概览", assets: "资产", vouchers: "代金券", permissions: "权限", quarantine: "隔离", send: "发送", receive: "接收", history: "历史记录", backup: "备份", walletSettings: "钱包设置", general: "常规", security: "安全", policies: "策略", advanced: "高级", telemetry: "遥测", interfaces: "接口", entrypoints: "入口点", paths: "路径", probes: "探针", links: "链接", privacy: "隐私", transport: "传输", queues: "队列", ingress: "入口", planning: "规划", placement: "放置", publication: "发布", recovery: "恢复", watchers: "监测器", alerts: "警报", publicationChecks: "发布检查", daProviders: "DA 提供商", censorship: "审查信号", evidenceExport: "导出证据", explorer: "浏览器", search: "搜索", checkpoints: "检查点", batches: "批次", publicEvidence: "公开证据", discover: "发现 dApps", connections: "连接", activity: "活动", messenger: "信使", inbox: "收件箱", sent: "已发送", requests: "请求", conversations: "会话", outbox: "发件箱", receipts: "回执", contacts: "联系人", settings: "设置", appearance: "外观", help: "帮助", logOut: "退出登录", roadmap: "路线图" }
  });

  const supplementalTranslations = Object.freeze({
    ru: { import: "Импорт", mergeSplit: "Объединить/разделить", stake: "Стейкинг", unstake: "Вывести из стейкинга", network: "Сеть", dataStorage: "Данные и хранилище", diskUsage: "Использование диска", networkUsage: "Использование сети", notifications: "Уведомления", about: "О приложении" },
    fr: { import: "Importer", stake: "Staker", unstake: "Retirer du staking", network: "Réseau", dataStorage: "Données et stockage", diskUsage: "Utilisation du disque", networkUsage: "Utilisation du réseau", notifications: "Notifications", about: "À propos" },
    de: { import: "Importieren", stake: "Staken", unstake: "Unstaken", network: "Netzwerk", dataStorage: "Daten und Speicher", diskUsage: "Speichernutzung", networkUsage: "Netzwerknutzung", notifications: "Benachrichtigungen", about: "Über" },
    es: { import: "Importar", stake: "Hacer staking", unstake: "Retirar staking", network: "Red", dataStorage: "Datos y almacenamiento", diskUsage: "Uso del disco", networkUsage: "Uso de red", notifications: "Notificaciones", about: "Acerca de" },
    pt: { import: "Importar", stake: "Fazer staking", unstake: "Retirar staking", network: "Rede", dataStorage: "Dados e armazenamento", diskUsage: "Utilização do disco", networkUsage: "Utilização da rede", notifications: "Notificações", about: "Sobre" },
    ko: { import: "가져오기", stake: "스테이킹", unstake: "언스테이킹", network: "네트워크", dataStorage: "데이터 및 저장 공간", diskUsage: "디스크 사용량", networkUsage: "네트워크 사용량", notifications: "알림", about: "정보" },
    tr: { import: "İçe aktar", stake: "Stake et", unstake: "Stake’den çıkar", network: "Ağ", dataStorage: "Veri ve Depolama", diskUsage: "Disk Kullanımı", networkUsage: "Ağ Kullanımı", notifications: "Bildirimler", about: "Hakkında" },
    ja: { import: "インポート", stake: "ステーク", unstake: "アンステーク", network: "ネットワーク", dataStorage: "データとストレージ", diskUsage: "ディスク使用量", networkUsage: "ネットワーク使用量", notifications: "通知", about: "このアプリについて" },
    "zh-Hans": { import: "导入", stake: "质押", unstake: "解除质押", network: "网络", dataStorage: "数据与存储", diskUsage: "磁盘使用情况", networkUsage: "网络使用情况", notifications: "通知", about: "关于" }
  });

  i18n.extendLocale("en", { navigation: english });
  Object.entries(translations).forEach(([language, labels]) => {
    const activeLabels = Object.fromEntries(
      Object.entries(labels).filter(([key]) => key !== "connections")
    );
    i18n.extendLocale(language, { navigation: { ...english, ...activeLabels, ...supplementalTranslations[language] } });
  });
})();
