"use strict";

window.Z00ZI18n.registerLocale("pt", {
  common: { unavailable: "Indisponível", readOnly: "Só de leitura", chain: "Cadeia", chainLocked: "Escolha com cuidado. A cadeia não pode ser alterada após a criação da carteira.", on: "Ligado", off: "Desligado", close: "Fechar" },
  app: {
    documentTitle: "Z00Z Wallet — Conceito interativo", wallets: "Carteiras", network: "Rede", addWallet: "Adicionar carteira", removeWallet: "Remover carteira", settings: "Definições", home: "Início",
    homeContext: "O seu dinheiro privado num relance", settingsContext: "Preferências da aplicação", walletContext: "Carteira {wallet}", interactiveConcept: "Conceito interativo · sem fundos reais", conceptBuild: "Conceito 0.4 · sem fundos reais", logOut: "Terminar sessão",
    general: "Geral", language: "Idioma", languageHelp: "Idioma utilizado em toda esta aplicação de carteira", notifications: "Notificações", notificationsHelp: "Mostrar atualizações da carteira e ações necessárias",
    regionalFormat: "Formato regional", regionalFormatHelp: "Controla datas, números e separadores decimais independentemente do idioma", timeZone: "Fuso horário", timeZoneHelp: "As marcas temporais são guardadas em UTC e apresentadas neste fuso horário",
    networkUnits: "Unidades de rede", networkUnitsHelp: "As velocidades de rede usam bits decimais por segundo", decimalBitrate: "Bits decimais por segundo", translationCoverage: "Cobertura de tradução", translationCoverageHelp: "{count} catálogos de idiomas estão sincronizados com as chaves de origem em inglês", languageChanged: "Idioma alterado localmente."
  },
  nav: { home: "Início", assets: "Ativos", history: "Histórico", swap: "Troca", exchange: "Câmbio", staking: "Staking", backup: "Cópia de segurança", settings: "Definições" },
  network: { routeTelemetry: "Telemetria de rotas", carrierTelemetry: "Telemetria de transporte", publicationTelemetry: "Telemetria de publicação" },
  walletShell: {
    balanceAvailable: "{value} disponível", current: "Atual", scanning: "A analisar", identityAria: "Mudar de carteira. Carteira atual: {wallet}", lockLabel: "Carteira {wallet}", copyAddress: "Copiar o endereço completo da carteira {wallet}",
    available: "Disponível", locked: "Bloqueado", pendingIn: "Entrada pendente", pendingOut: "Saída pendente", routeTelemetry: "Telemetria de rotas"
  },
  assets: {
    wallet: "Carteira", sections: "Secções da carteira", sectionAssets: "Ativos", sectionAssetsHelp: "Valor disponível e detido", sectionVouchers: "Vales", sectionVouchersHelp: "Valor condicional", sectionPermissions: "Permissões", sectionPermissionsHelp: "Autoridade limitada",
    family: "Família de ativos", title: "Os seus ativos", description: "Dinheiro nativo, tokens emitidos e colecionáveis permanecem distintos. Apenas dinheiro nativo utilizável entra em Disponível.", send: "Enviar", moneyTotals: "Totais monetários", available: "Disponível", readyToUse: "Pronto a usar", receiving: "A receber", sending: "A enviar", waitingToSettle: "A aguardar liquidação",
    filters: "Filtros de ativos", all: "Todos", filterCoins: "Moedas", filterTokens: "Tokens", filterNfts: "NFT", kindCoin: "Moeda", kindToken: "Token", kindCollectible: "NFT", needsReview: "Requer revisão", owned: "Ativos detidos", ownedHelp: "Classe, confiança e possibilidade de utilização são explícitas", name: "Nome", balance: "Saldo", value: "Valor", price: "Preço",
    viewDetails: "Ver detalhes de {asset}", receiveAsset: "Receber {asset}", sendAsset: "Enviar {asset}", receive: "Receber", noMarketFeed: "Sem fonte de mercado", nativeCatalog: "Ativo nativo · catálogo fidedigno", declaredDomain: "Domínio declarado · revisão necessária", uniqueCollectible: "Colecionável único · metadados disponíveis", excludedNotice: "Vales, permissões, objetos em quarentena, tokens não nativos, colecionáveis e ativos de compatibilidade experimental são excluídos de Disponível.",
    noVouchers: "Ainda não há vales", noVouchersHelp: "Crie um vale quando esta carteira precisar de valor condicional transferível.", createVoucher: "Criar vale", noPermissions: "Ainda não há permissões", noPermissionsHelp: "Crie uma permissão limitada quando esta carteira precisar de autoridade transferível.", createPermission: "Criar permissão"
  },
  history: {
    honestSettlement: "Liquidação transparente", title: "Tudo o que mudou", description: "A submissão e a liquidação final são apresentadas como estados distintos. Abra um item para ver o recibo e a linha temporal técnica.", filters: "Filtros do histórico", all: "Todos", assets: "Ativos", vouchers: "Vales", permissions: "Permissões", system: "Sistema", needsAttention: "Requer atenção", search: "Pesquisar histórico", results: "Resultados do histórico",
    settling: "Em liquidação", settled: "Liquidado", active: "Ativo", ready: "Pronto", paymentTo: "Pagamento a {recipient}", sentWaiting: "Enviado · a aguardar liquidação", allocationClaimed: "Alocação reclamada", verifiedClaimWaiting: "Reclamação verificada · a aguardar liquidação", receivedFrom: "Recebido de {sender}", yesterday: "Ontem", travelRefundVoucher: "Vale de reembolso de viagem", offeredReviewBefore: "Oferecido · rever antes de {date}", deliveryReceiptAccess: "Acesso ao recibo de entrega", dataAccessUsesRemain: "Acesso a dados · restam {used} de {total} utilizações", uses: "{count} utilizações", jul12: "12 jul.", localBackupCreated: "Cópia de segurança local criada", integrityPassed: "Verificação de integridade aprovada", jul10: "10 jul.", transferFrom: "Transferência de {wallet}", jul3: "3 jul.", recoveryCheckCompleted: "Verificação de recuperação concluída", localVerificationPassed: "Verificação local aprovada", jun30: "30 jun.", jul21: "21 jul.", waitingToSettle: "A aguardar liquidação", minutesAgo: "há {count} min", noMatching: "Sem histórico correspondente", tryAnother: "Experimente outro filtro ou termo de pesquisa.", details: "Detalhes do histórico", status: "Estado", when: "Quando", fee: "Comissão", feeIncluded: "Incluída", feeNotApplicable: "Não aplicável", privacy: "Privacidade", privacyValue: "Simulação-alvo · não é telemetria em direto", carrierChain: "Transporte e cadeia", carrierChainValue: "Alvo Reticulum · simulação principal", technicalDetails: "Detalhes técnicos", idLabel: "ID", lifecycleLabel: "Ciclo de vida", lifecyclePending: "criado → submetido → admitido", lifecycleConfirmed: "criado → submetido → admitido → confirmado", receiptLabel: "Recibo", copyReceipt: "Copiar recibo", done: "Concluído"
  },
  staking: {
    eyebrow: "Staking da carteira", heading: "Fazer staking a partir de {wallet}", description: "Os termos de staking e o valor pendente mantêm-se distintos do saldo Disponível utilizável da carteira.", badge: "Principal · conceito", totals: "Totais de staking", availableToStake: "Disponível para staking", walletValueBefore: "Valor da carteira antes de submeter staking", staked: "Em staking", nothingDelegated: "Nada delegado neste conceito", rewards: "Recompensas", accrualNotSimulated: "A acumulação não é simulada", prepare: "Preparar staking", prepareHelp: "Escolha o montante e inspecione os termos do validador antes da autorização.", amount: "Montante", availableBalance: "Disponível: {value}", validator: "Validador", validatorPlaceholder: "Escolha após a verificação da cadeia", review: "Rever staking", safeguards: "Proteções de staking", validatorStatus: "Estado do validador", unlockPeriod: "Período de desbloqueio", notSelected: "Não selecionado", notProjected: "Não projetado", notice: "O conceito nunca estima o rendimento nem oculta o risco de bloqueio. Um staking permanece pendente até à liquidação na cadeia."
  },
  settings: { sections: "Secções das definições", application: "Aplicação", connectivity: "Conectividade", general: "Geral", generalHelp: "Idioma e notificações da aplicação", appearance: "Aspeto", appearanceHelp: "Tema, paleta, densidade e realce YAML", networkPrivacy: "Rede", networkPrivacyHelp: "Rota privada, cadeia e sincronização", networkSections: "Secções de rede", overview: "Visão geral" },
  walletSettings: {
    password: "Palavra-passe da carteira", passwordHelp: "Altere esta palavra-passe localmente. A palavra-passe atual é necessária antes de aceitar uma nova.", changePassword: "Alterar palavra-passe", changePasswordTitle: "Alterar palavra-passe da carteira", changePasswordSubtitle: "Confirme a palavra-passe atual e escolha uma nova", currentPassword: "Palavra-passe atual", newPassword: "Nova palavra-passe", confirmNewPassword: "Confirmar nova palavra-passe", passwordChangeHint: "Utilize pelo menos 8 carateres. As palavras-passe são limpas imediatamente da demonstração.", changePasswordSubmit: "Alterar palavra-passe", passwordChangedTitle: "Palavra-passe atualizada", passwordChangedResult: "A palavra-passe foi alterada apenas neste conceito local. A demonstração limpa todas as entradas e não retém nenhum segredo.", passwordCurrentError: "Introduza a palavra-passe atual (pelo menos 8 carateres).", passwordNewError: "Utilize pelo menos 8 carateres para a nova palavra-passe.", passwordSameError: "Escolha uma palavra-passe diferente da atual.", passwordMismatchError: "As novas palavras-passe não coincidem."
  },
  reticulum: { title: "Telemetria Reticulum", summary: "Uma vista apenas local de evidência de transporte e entrega. Apoia decisões de disponibilidade sem transformar metadados de transporte em análises de utilizador.", localCapability: "Capacidade local indisponível", localCapabilityHelp: "Esta demonstração de carteira não tem uma ponte de estado local Reticulum registada. Não são inventados dados de transporte com aspeto real.", tabs: { overview: "Visão geral", node: "Nó", interfaces: "Interfaces", radio: "Rádio", entrypoints: "Pontos de entrada", paths: "Caminhos", probes: "Sondas", links: "Ligações" } },
  aggregators: { title: "Telemetria de agregadores", summary: "Evidência de serviço e publicação apenas para leitura para trabalho de agregação. Nunca recebe chaves, seeds ou segredos de política da carteira.", localCapability: "Capacidade local indisponível", localCapabilityHelp: "A carteira não tem uma ponte registada para o instantâneo de estado do agregador; por isso esta página mostra corretamente indisponível.", tabs: { overview: "Visão geral" } },
  onionnet: { title: "Telemetria OnionNet", summary: "Uma vista consciente de limites do estado determinístico do plano de controlo, evidência local e saúde sintética agregada. Este espaço nunca altera uma rota ou política de privacidade.", localCapability: "Capacidade local indisponível", localCapabilityHelp: "Esta demonstração de carteira não tem uma ponte de estado OnionNet registada. Não são inventados valores de rota, topologia ou privacidade com aspeto real.", tabs: { overview: "Visão geral", epoch: "Época", privacy: "Privacidade", transport: "Transporte", queues: "Filas e repetição", probation: "Período de prova", ingress: "Entrada" } },
  status: { up: "Ativo", down: "Inativo", connecting: "A ligar", degraded: "Degradado" },
  units: { bitPerSecond: "{value} bit/s", kilobitPerSecond: "{value} kbit/s", megabitPerSecond: "{value} Mbit/s" }
});
