"use strict";

window.Z00ZI18n.registerLocale("tr", {
  common: { unavailable: "Kullanılamıyor", readOnly: "Salt okunur", chain: "Zincir", chainLocked: "Dikkatle seçin. Cüzdan oluşturulduktan sonra zincir değiştirilemez.", on: "Açık", off: "Kapalı", close: "Kapat", back: "Geri" },
  app: {
    documentTitle: "Z00Z Wallet — Etkileşimli kavram", menu: "Menü", wallets: "Cüzdanlar", network: "Ağ", addWallet: "Cüzdan ekle", removeWallet: "Cüzdanı kaldır", settings: "Ayarlar", home: "Ana sayfa",
    homeContext: "Özel paranıza bir bakış", settingsContext: "Uygulama tercihleri", walletContext: "{wallet} cüzdanı", interactiveConcept: "Etkileşimli kavram · gerçek fon yok", conceptBuild: "Kavram 0.4 · gerçek fon yok", logOut: "Oturumu kapat",
    general: "Genel", language: "Dil", languageHelp: "Bu cüzdan uygulamasının tamamında kullanılan dil", notifications: "Bildirimler", notificationsHelp: "Cüzdan güncellemelerini ve gerekli işlemleri göster",
    regionalFormat: "Bölgesel biçim", regionalFormatHelp: "Dilinden bağımsız olarak tarihleri, sayıları ve ondalık ayırıcıları yönetir", timeZone: "Saat dilimi", timeZoneHelp: "Zaman damgaları UTC olarak saklanır ve bu saat diliminde gösterilir",
    networkUnits: "Ağ birimleri", networkUnitsHelp: "Ağ hızları saniye başına ondalık bit kullanır", decimalBitrate: "Saniye başına ondalık bit", translationCoverage: "Çeviri kapsamı", translationCoverageHelp: "{count} dil kataloğu İngilizce kaynak anahtarlarıyla eşzamanlıdır", languageChanged: "Dil yerel olarak değiştirildi."
  },
  nav: { home: "Ana sayfa", assets: "Varlıklar", history: "Geçmiş", swap: "Takas", exchange: "Borsa", staking: "Stake", backup: "Yedek", settings: "Ayarlar" },
  network: { routeTelemetry: "Rota telemetrisi", carrierTelemetry: "Taşıyıcı telemetrisi", publicationTelemetry: "Yayın telemetrisi" },
  walletShell: {
    balanceAvailable: "{value} kullanılabilir", current: "Geçerli", scanning: "Taranıyor", identityAria: "Cüzdan değiştir. Geçerli cüzdan: {wallet}", lockLabel: "{wallet} cüzdanı", copyAddress: "{wallet} cüzdanının tam adresini kopyala",
    available: "Kullanılabilir", locked: "Kilitli", pendingIn: "Giriş bekliyor", pendingOut: "Çıkış bekliyor", routeTelemetry: "Rota telemetrisi"
  },
  assets: {
    wallet: "Cüzdan", sections: "Cüzdan bölümleri", sectionAssets: "Varlıklar", sectionAssetsHelp: "Harcanabilir ve sahip olunan değer", sectionVouchers: "Kuponlar", sectionVouchersHelp: "Koşullu değer", sectionPermissions: "İzinler", sectionPermissionsHelp: "Sınırlı yetki",
    family: "Varlık ailesi", title: "Varlıklarınız", description: "Yerel para, ihraç edilen tokenler ve koleksiyon varlıkları ayırt edilebilir kalır. Kullanılabilir alanına yalnızca harcanabilir yerel para girer.", send: "Gönder", moneyTotals: "Para toplamları", available: "Kullanılabilir", readyToUse: "Kullanıma hazır", receiving: "Alınıyor", sending: "Gönderiliyor", waitingToSettle: "Kesinleşme bekleniyor",
    filters: "Varlık filtreleri", all: "Tümü", filterCoins: "Coinler", filterTokens: "Tokenler", filterNfts: "NFT'ler", kindCoin: "Coin", kindToken: "Token", kindCollectible: "NFT", needsReview: "İnceleme gerekli", owned: "Sahip olunan varlıklar", ownedHelp: "Sınıf, güven ve harcanabilirlik açıkça belirtilir", name: "Ad", balance: "Bakiye", value: "Değer", price: "Fiyat",
    viewDetails: "{asset} ayrıntılarını görüntüle", receiveAsset: "{asset} al", sendAsset: "{asset} gönder", receive: "Al", noMarketFeed: "Piyasa verisi yok", nativeCatalog: "Yerel varlık · güvenilir katalog", declaredDomain: "Beyan edilmiş alan adı · inceleme gerekli", uniqueCollectible: "Benzersiz koleksiyon varlığı · meta veri kullanılabilir", excludedNotice: "Kuponlar, izinler, karantinaya alınmış nesneler, yerel olmayan tokenler, koleksiyon varlıkları ve deneysel uyumluluk varlıkları Kullanılabilir alanından hariç tutulur.",
    noVouchers: "Henüz kupon yok", noVouchersHelp: "Bu cüzdan aktarılabilir koşullu değere ihtiyaç duyduğunda bir kupon oluşturun.", createVoucher: "Kupon oluştur", noPermissions: "Henüz izin yok", noPermissionsHelp: "Bu cüzdan aktarılabilir yetkiye ihtiyaç duyduğunda sınırlı bir izin oluşturun.", createPermission: "İzin oluştur"
  },
  history: {
    honestSettlement: "Şeffaf kesinleşme", title: "Değişen her şey", description: "Gönderim ve nihai kesinleşme farklı durumlar olarak gösterilir. Makbuzu ve teknik zaman çizelgesini görmek için bir öğe açın.", filters: "Geçmiş filtreleri", all: "Tümü", assets: "Varlıklar", vouchers: "Kuponlar", permissions: "İzinler", system: "Sistem", needsAttention: "Dikkat gerekli", search: "Geçmişte ara", results: "Geçmiş sonuçları",
    settling: "Kesinleşiyor", settled: "Kesinleşti", active: "Etkin", ready: "Hazır", paymentTo: "{recipient} için ödeme", sentWaiting: "Gönderildi · kesinleşme bekleniyor", allocationClaimed: "Tahsis alındı", verifiedClaimWaiting: "Talep doğrulandı · kesinleşme bekleniyor", receivedFrom: "{sender} kişisinden alındı", yesterday: "Dün", travelRefundVoucher: "Seyahat iade kuponu", offeredReviewBefore: "Sunuldu · {date} öncesinde inceleyin", deliveryReceiptAccess: "Teslim makbuzu erişimi", dataAccessUsesRemain: "Veri erişimi · {total} kullanımın {used} tanesi kaldı", uses: "{count} kullanım", jul12: "12 Tem", localBackupCreated: "Yerel yedek oluşturuldu", integrityPassed: "Bütünlük denetimi geçti", jul10: "10 Tem", transferFrom: "{wallet} cüzdanından aktarım", jul3: "3 Tem", recoveryCheckCompleted: "Kurtarma denetimi tamamlandı", localVerificationPassed: "Yerel doğrulama geçti", jun30: "30 Haz", jul21: "21 Tem", waitingToSettle: "Kesinleşme bekleniyor", minutesAgo: "{count} dk önce", noMatching: "Eşleşen geçmiş yok", tryAnother: "Başka bir filtre veya arama terimi deneyin.", details: "Geçmiş ayrıntıları", status: "Durum", when: "Ne zaman", fee: "Ücret", feeIncluded: "Dahil", feeNotApplicable: "Uygulanamaz", privacy: "Gizlilik", privacyValue: "Hedef simülasyonu · canlı telemetri değil", carrierChain: "Taşıyıcı ve zincir", carrierChainValue: "Reticulum hedefi · ana simülasyon", technicalDetails: "Teknik ayrıntılar", idLabel: "Kimlik", lifecycleLabel: "Yaşam döngüsü", lifecyclePending: "oluşturuldu → gönderildi → kabul edildi", lifecycleConfirmed: "oluşturuldu → gönderildi → kabul edildi → onaylandı", receiptLabel: "Makbuz", copyReceipt: "Makbuzu kopyala", done: "Bitti"
  },
  staking: {
    eyebrow: "Cüzdan stake'i", heading: "{wallet} üzerinden stake et", description: "Stake koşulları ve bekleyen değer, cüzdanın harcanabilir Kullanılabilir bakiyesinden ayrı kalır.", badge: "Ana · kavram", totals: "Stake toplamları", availableToStake: "Stake edilebilir", walletValueBefore: "Stake gönderilmeden önce cüzdan değeri", staked: "Stake edildi", nothingDelegated: "Bu kavramda hiçbir şey devredilmedi", rewards: "Ödüller", accrualNotSimulated: "Birikim simüle edilmez", prepare: "Stake hazırla", prepareHelp: "Yetkilendirmeden önce tutarı seçin ve doğrulayıcı koşullarını inceleyin.", amount: "Tutar", availableBalance: "Kullanılabilir: {value}", validator: "Doğrulayıcı", validatorPlaceholder: "Zincir doğrulamasından sonra seçin", review: "Stake'i incele", safeguards: "Stake güvenceleri", validatorStatus: "Doğrulayıcı durumu", unlockPeriod: "Kilit açma süresi", notSelected: "Seçilmedi", notProjected: "Öngörülmedi", notice: "Bu kavram hiçbir zaman getiri tahmini yapmaz veya kilitlenme riskini gizlemez. Bir stake, zincir kesinleşene kadar beklemede kalır."
  },
  settings: { sections: "Ayar bölümleri", application: "Uygulama", connectivity: "Bağlantı", general: "Genel", generalHelp: "Dil ve uygulama bildirimleri", appearance: "Görünüm", appearanceHelp: "Tema, palet, yoğunluk ve YAML vurgulama", networkPrivacy: "Ağ", networkPrivacyHelp: "Özel rota, zincir ve eşzamanlama", networkSections: "Ağ bölümleri", overview: "Genel bakış" },
  walletSettings: {
    password: "Cüzdan parolası", passwordHelp: "Bu cüzdan parolasını yerel olarak değiştirin. Yeni parola kabul edilmeden önce geçerli parola gereklidir.", changePassword: "Parolayı değiştir", changePasswordTitle: "Cüzdan parolasını değiştir", changePasswordSubtitle: "Geçerli parolayı doğrulayın, sonra yeni bir parola seçin", currentPassword: "Geçerli parola", newPassword: "Yeni parola", confirmNewPassword: "Yeni parolayı doğrula", passwordChangeHint: "En az 8 karakter kullanın. Parolalar demodan hemen temizlenir.", changePasswordSubmit: "Parolayı değiştir", passwordChangedTitle: "Parola güncellendi", passwordChangedResult: "Parola yalnızca bu yerel kavramda değiştirildi. Demo tüm girişleri temizler ve hiçbir sırrı saklamaz.", passwordCurrentError: "Geçerli parolayı girin (en az 8 karakter).", passwordNewError: "Yeni parola için en az 8 karakter kullanın.", passwordSameError: "Geçerli paroladan farklı bir parola seçin.", passwordMismatchError: "Yeni parolalar eşleşmiyor."
  },
  reticulum: { title: "Reticulum telemetrisi", summary: "Taşıyıcı ve teslimat kanıtlarının yalnızca yerel görünümüdür. Taşıma meta verilerini kullanıcı analizine dönüştürmeden kullanılabilirlik kararlarını destekler.", localCapability: "Yerel yetenek kullanılamıyor", localCapabilityHelp: "Bu cüzdan demosunda kayıtlı yerel Reticulum durum köprüsü yok. Gerçek gibi görünen taşıyıcı verileri oluşturulmaz.", tabs: { overview: "Genel bakış", node: "Düğüm", interfaces: "Arayüzler", radio: "Radyo", entrypoints: "Giriş noktaları", paths: "Yollar", probes: "Sondalar", links: "Bağlantılar" } },
  aggregators: { title: "Toplayıcı telemetrisi", summary: "Toplama işleri için salt okunur hizmet ve yayın kanıtları. Hiçbir zaman cüzdan anahtarlarını, seed ifadelerini veya politika sırlarını almaz.", localCapability: "Yerel yetenek kullanılamıyor", localCapabilityHelp: "Cüzdanın toplayıcı durum anlık görüntüsüne kayıtlı bir köprüsü yoktur; bu nedenle sayfa doğru olarak kullanılamıyor gösterir.", tabs: { overview: "Genel bakış" } },
  onionnet: { title: "OnionNet telemetrisi", summary: "Belirleyici denetim düzlemi durumu, yerel kanıtlar ve toplu sentetik sağlık için sınır farkındalığı olan görünüm. Bu çalışma alanı hiçbir zaman rotayı veya gizlilik politikasını değiştirmez.", localCapability: "Yerel yetenek kullanılamıyor", localCapabilityHelp: "Bu cüzdan demosunda kayıtlı OnionNet durum köprüsü yok. Gerçek gibi görünen rota, topoloji veya gizlilik değerleri oluşturulmaz.", tabs: { overview: "Genel bakış", epoch: "Dönem", privacy: "Gizlilik", transport: "Taşıma", queues: "Kuyruklar ve yeniden oynatma", probation: "Deneme", ingress: "Giriş" } },
  help: { title: "Yardım", openGlobal: "Uygulama yardımını aç", openContext: "Bu görünüm için yardım", close: "Yardımı kapat", contents: "İçindekiler", section: "Yardım bölümü {current}/{total}", unavailable: "Bu görünüm için yardım kullanılamıyor." },
  status: { up: "Çalışıyor", down: "Kapalı", connecting: "Bağlanıyor", degraded: "Düşük performans" },
  units: { bitPerSecond: "{value} bit/sn", kilobitPerSecond: "{value} kbit/sn", megabitPerSecond: "{value} Mbit/sn" }
});
