#![allow(unexpected_cfgs)]
#![cfg(kani)]

// GENERATED BY z00z-verification-artifact-builder
#[allow(unreachable_pub)]
#[path = "fixtures/generated_kani/generated_kani_asset_pkg.rs"]
mod fixtures;

#[kani::proof]
fn test_version_partition_total() {
    let serial: u32 = kani::any();
    let version = z00z_core::assets::validate_serial_id_version(serial);
    if serial <= 999_999 {
        assert_eq!(version, z00z_core::assets::AssetPackVersion::Basic);
    } else if serial <= 1_999_999 {
        assert_eq!(version, z00z_core::assets::AssetPackVersion::Memo);
    } else {
        assert_eq!(version, z00z_core::assets::AssetPackVersion::Unknown);
    }
}

#[kani::proof]
fn test_unknown_lane_rejects() {
    let err = z00z_core::assets::decode_asset_pack(
        &[0u8; 72],
        z00z_core::assets::AssetPackVersion::Unknown,
    )
    .expect_err("unknown lane must reject");
    assert_eq!(err, z00z_core::assets::PackErr::BadVer);
}

#[kani::proof]
fn test_basic_fixture_decodes() {
    let decoded = z00z_core::assets::decode_asset_pack(
        fixtures::ASSET_PACK_BASIC,
        z00z_core::assets::AssetPackVersion::Basic,
    )
    .expect("decode basic fixture");
    assert!(matches!(
        decoded,
        z00z_core::assets::DecodedAssetPack::Basic(_)
    ));
}
