#!/usr/bin/env python3
"""Bootstrap missing Z00Z verification artifacts from current repository surfaces."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import textwrap
from datetime import datetime, timezone
from pathlib import Path


GEN_MARKER = "GENERATED BY z00z-verification-artifact-builder"
PROMPT_FILE_SUFFIXES = {".md", ".txt", ".yaml", ".yml", ".py", ".sh", ".toml", ".json"}
DOMAIN_RE = re.compile(
    r'hash_domain!\s*\(\s*(?P<name>[A-Za-z0-9_]+)\s*,\s*"(?P<label>[^"]+)"\s*,\s*(?P<version>[0-9]+)\s*\)',
    re.DOTALL,
)
SECURITY_PROMPT_TERMS = {
    "adversarial-review": ("adversarial", "red-team", "break", "jailbreak", "abuse", "bypass"),
    "attack-surface": ("attack surface", "threat", "exploit", "misuse", "replay", "forg", "tamper"),
    "crypto-review": ("crypto", "cryptographic", "transcript", "domain separation", "proof", "signature", "stealth"),
    "fuzz-parser": ("fuzz", "parser", "decode", "deserialize", "compact", "untrusted input"),
    "unsafe-ub": ("unsafe", "ub", "miri", "undefined behavior"),
    "supply-chain": ("supply-chain", "dependency", "audit", "semver"),
}
SECURITY_FAMILIES = [
    {
        "id": "checkpoint-lineage",
        "title": "Checkpoint lineage and delta integrity",
        "severity": "high",
        "categories": ["adversarial-review", "attack-surface", "crypto-review"],
        "prefixes": [
            "crates/z00z_storage/src",
            "crates/z00z_runtime/aggregators/src",
            "crates/z00z_runtime/validators/src",
            "crates/z00z_runtime/watchers/src",
        ],
        "terms": ["checkpoint", "root", "delta"],
        "probe_questions": [
            "Can one crate accept a root transition that another crate later rejects as stale or already spent?",
            "Can spent and created deltas stay locally balanced while cross-crate lineage still forks?",
        ],
    },
    {
        "id": "payment-request-replay",
        "title": "PaymentRequest replay and compact-request rebinding",
        "severity": "high",
        "categories": ["adversarial-review", "attack-surface", "crypto-review", "fuzz-parser"],
        "prefixes": [
            "crates/z00z_wallets/src",
            "crates/z00z_storage/src",
            "crates/z00z_runtime/validators/src",
            "crates/z00z_crypto/src",
        ],
        "terms": ["payment", "request", "replay"],
        "probe_questions": [
            "Can the same compact request be replayed across epochs, chain ids, or validator contexts?",
            "Can a request stay signature-valid while being rebound to a different domain or receiver context?",
        ],
    },
    {
        "id": "voucher-rights-transfer",
        "title": "Voucher acceptance and rights-transfer bypass",
        "severity": "high",
        "categories": ["adversarial-review", "attack-surface", "crypto-review"],
        "prefixes": [
            "crates/z00z_core/src",
            "crates/z00z_storage/src",
            "crates/z00z_wallets/src",
        ],
        "terms": ["voucher", "rights", "transfer"],
        "probe_questions": [
            "Can a non-transferable right become redeemable through wrapper, cache, or voucher indirection?",
            "Can refusal and acceptance states diverge across crates for the same voucher lineage?",
        ],
    },
    {
        "id": "stealth-inbox-delivery",
        "title": "Stealth delivery and inbox notification confusion",
        "severity": "high",
        "categories": ["adversarial-review", "attack-surface", "crypto-review"],
        "prefixes": [
            "crates/z00z_wallets/src",
            "crates/z00z_crypto/src",
            "crates/z00z_networks_rpc/src",
        ],
        "terms": ["stealth", "inbox", "notify"],
        "probe_questions": [
            "Can a notification be rebound to a different receiver while preserving a plausible owner tag?",
            "Can delivery and observation paths disagree on what metadata authenticates a stealth notice?",
        ],
    },
    {
        "id": "transcript-domain-binding",
        "title": "Transcript and domain-separation drift",
        "severity": "high",
        "categories": ["adversarial-review", "crypto-review"],
        "prefixes": [
            "crates/z00z_crypto/src",
            "crates/z00z_wallets/src",
            "crates/z00z_storage/src",
            "crates/z00z_core/src",
        ],
        "terms": ["transcript", "domain", "proof"],
        "probe_questions": [
            "Can two proof families share a challenge transcript layout while believing they are domain-separated?",
            "Can version or serialization drift keep one crate's challenge binding compatible with another crate's older meaning?",
        ],
    },
    {
        "id": "compact-wire-parsers",
        "title": "Compact-wire and decoder abuse surface",
        "severity": "medium",
        "categories": ["adversarial-review", "attack-surface", "fuzz-parser", "unsafe-ub"],
        "prefixes": [
            "crates/z00z_core/src",
            "crates/z00z_storage/src",
            "crates/z00z_wallets/src",
            "crates/z00z_crypto/src",
        ],
        "terms": ["decode", "parse", "compact"],
        "probe_questions": [
            "Can malformed bytes trigger panic-only rejection instead of structured failure?",
            "Can parser disagreement across crates create type confusion or silent truncation?",
        ],
    },
]
RUN_ROOT_RE = re.compile(
    r"^reports/z00z-verification-orchestrator-\d{8}-\d{6}$"
)


def repo_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def rel_between(base: Path, target: Path) -> str:
    return Path(os.path.relpath(target, base)).as_posix()


def normalize_runtime_root(root: Path, requested: str | None, default_rel: str) -> str:
    if not requested:
        return default_rel
    path = Path(requested)
    if not path.is_absolute():
        path = (root / path).resolve()
    else:
        path = path.resolve()
    try:
        return path.relative_to(root).as_posix()
    except ValueError as exc:
        raise ValueError(f"runtime root must stay inside repository: {path}") from exc


def canonical_run_root_rel(report_stamp: str) -> str:
    return f"reports/z00z-verification-orchestrator-{report_stamp}"


def ensure_canonical_run_root_rel(run_root_rel: str) -> None:
    if not RUN_ROOT_RE.fullmatch(run_root_rel):
        raise ValueError(
            f"verification run root must be reports/z00z-verification-orchestrator-<YYYYMMDD-HHMMSS>: {run_root_rel}"
        )


def ensure_report_local_runtime_root(label: str, runtime_root_rel: str, run_root_rel: str) -> None:
    if runtime_root_rel == run_root_rel:
        return
    if runtime_root_rel.startswith(f"{run_root_rel}/"):
        return
    raise ValueError(
        f"{label} must live under {run_root_rel}/..., got {runtime_root_rel}"
    )


def is_generated_file(path: Path) -> bool:
    if not path.exists():
        return False
    head = path.read_text(encoding="utf-8", errors="replace").splitlines()[:4]
    return any(GEN_MARKER in line for line in head)


def cargo_metadata(root: Path) -> dict:
    result = subprocess.run(
        ["cargo", "metadata", "--no-deps", "--format-version", "1"],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def scan_domain_defs(root: Path) -> list[dict[str, str]]:
    records: list[dict[str, str]] = []
    crates_dir = root / "crates"
    for path in sorted(crates_dir.rglob("*.rs")):
        path_text = path.as_posix()
        if "/tari/" in path_text:
            continue
        for match in DOMAIN_RE.finditer(repo_text(path)):
            records.append(
                {
                    "name": match.group("name"),
                    "label": match.group("label"),
                    "version": match.group("version"),
                    "file": rel(path, root),
                }
            )
    return records


def files_with_terms(root: Path, prefixes: list[str], terms: list[str], limit: int = 8) -> list[str]:
    needles = [term.lower() for term in terms]
    matches: list[str] = []
    for prefix in prefixes:
        base = root / prefix
        if not base.exists():
            continue
        for path in sorted(base.rglob("*.rs")):
            path_text = path.as_posix()
            if "/tari/" in path_text:
                continue
            haystack = f"{path.name}\n{repo_text(path)}".lower()
            if all(term in haystack for term in needles):
                matches.append(rel(path, root))
            elif any(term in haystack for term in needles):
                matches.append(rel(path, root))
    deduped = sorted(dict.fromkeys(matches))
    return deduped[:limit]


def github_prompt_files(root: Path) -> list[Path]:
    github_root = root / ".github"
    if not github_root.exists():
        return []

    candidates: list[Path] = []
    for path in sorted(github_root.rglob("*")):
        if not path.is_file():
            continue
        if "__pycache__" in path.parts:
            continue
        if path.suffix.lower() not in PROMPT_FILE_SUFFIXES:
            continue
        candidates.append(path)
    return candidates


def prompt_source_kind(path: Path, root: Path) -> str:
    rel_path = rel(path, root)
    if "/scripts/" in rel_path:
        return "script"
    if "/templates/" in rel_path:
        return "template"
    if rel_path.startswith(".github/skills/"):
        return "skill"
    if rel_path.startswith(".github/agents/"):
        return "agent"
    if rel_path.startswith(".github/requirements/"):
        return "requirement"
    if rel_path.startswith(".github/instructions/"):
        return "instruction"
    if rel_path.startswith(".github/prompts/"):
        return "prompt"
    if rel_path.startswith(".github/gsd-core/workflows/"):
        return "workflow"
    if rel_path == ".github/copilot-instructions.md":
        return "instructions"
    return "other"


def classify_security_prompt_text(text: str) -> list[str]:
    lower = text.lower()
    categories: list[str] = []
    for category, terms in SECURITY_PROMPT_TERMS.items():
        if any(term in lower for term in terms):
            categories.append(category)
    return categories


def security_prompt_excerpts(text: str, limit: int = 8) -> list[str]:
    excerpts: list[str] = []
    for raw_line in text.splitlines():
        line = " ".join(raw_line.strip().split())
        if len(line) < 16:
            continue
        lower = line.lower()
        if not any(term in lower for terms in SECURITY_PROMPT_TERMS.values() for term in terms):
            continue
        excerpts.append(line[:220])
        if len(excerpts) >= limit:
            break
    return excerpts


def security_prompt_corpus(root: Path) -> str:
    entries: list[dict[str, object]] = []
    scanned_files = 0
    relevant_files = 0

    for path in github_prompt_files(root):
        if not path.is_file():
            continue
        scanned_files += 1
        text = repo_text(path)
        categories = classify_security_prompt_text(text)
        if not categories:
            continue
        relevant_files += 1
        excerpts = security_prompt_excerpts(text)
        entries.append(
            {
                "path": rel(path, root),
                "kind": prompt_source_kind(path, root),
                "categories": categories,
                "score": len(categories) + len(excerpts),
                "excerpt_count": len(excerpts),
                "excerpts": excerpts,
            }
        )

    payload = {
        "_generated_by": GEN_MARKER,
        "scanned_files": scanned_files,
        "relevant_files": relevant_files,
        "sources": sorted(entries, key=lambda item: (-int(item["score"]), str(item["path"]))),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def scope_match(paths: list[str], scope_kind: str, target_root_rel: str) -> list[str]:
    if scope_kind != "crate" or not target_root_rel:
        return paths
    scoped = [item for item in paths if item == target_root_rel or item.startswith(target_root_rel + "/")]
    return scoped


def crate_bucket(path: str) -> str:
    parts = path.split("/")
    if len(parts) < 2 or parts[0] != "crates":
        return "."
    if len(parts) >= 3 and parts[1] == "z00z_runtime" and parts[2] in {"validators", "aggregators", "watchers"}:
        return "/".join(parts[:3])
    return "/".join(parts[:2])


def ownership_for_paths(paths: list[str]) -> str:
    if not paths:
        return "project-owned"
    vendor_flags = ["/tari/" in f"/{item}/" or item.startswith("crates/z00z_crypto/tari/") for item in paths]
    if all(vendor_flags):
        return "protected-vendor"
    if any(vendor_flags):
        return "mixed"
    return "project-owned"


def attack_surface_registry(root: Path, scope_kind: str, target_root_rel: str, verification_root_rel: str) -> str:
    families: list[dict[str, object]] = []
    for family in SECURITY_FAMILIES:
        matches = files_with_terms(root, family["prefixes"], family["terms"], limit=20)
        matches = scope_match(matches, scope_kind, target_root_rel)
        if scope_kind == "crate" and target_root_rel and not matches:
            continue
        crates = sorted({crate_bucket(item) for item in matches})
        families.append(
            {
                "id": family["id"],
                "title": family["title"],
                "severity": family["severity"],
                "categories": family["categories"],
                "ownership": ownership_for_paths(matches),
                "crates": crates,
                "source_files": matches,
                "probe_questions": family["probe_questions"],
            }
        )

    payload = {
        "_generated_by": GEN_MARKER,
        "scope_kind": scope_kind,
        "target_root_rel": target_root_rel,
        "prompt_corpus_path": f"{verification_root_rel}/security/prompt_corpus.json",
        "families": families,
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def manual_or_owned_write(root: Path, path_str: str, content: str, summary: dict, kind: str) -> None:
    path = root / path_str
    path.parent.mkdir(parents=True, exist_ok=True)
    outcome = "created"
    if path.exists():
        current = path.read_text(encoding="utf-8", errors="replace")
        if current == content:
            summary["skipped"].append(
                {"path": path_str, "kind": kind, "reason": "up-to-date-generated-artifact"}
            )
            return
        if is_generated_file(path):
            outcome = "updated"
        else:
            summary["skipped"].append(
                {"path": path_str, "kind": kind, "reason": "manual-existing-artifact"}
            )
            return
    path.write_text(content, encoding="utf-8")
    summary[outcome].append({"path": path_str, "kind": kind})


def rust_string_literal(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def rust_bytes_literal(values: list[int], indent: str = "    ", width: int = 20) -> str:
    if not values:
        return f"{indent}\n"

    lines: list[str] = []
    for index in range(0, len(values), width):
        chunk = ", ".join(str(value) for value in values[index : index + width])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines) + "\n"


def kani_fixture_extract_cargo_toml(root: Path, extract_root: Path) -> str:
    core_rel = rel_between(extract_root, root / "crates/z00z_core")
    crypto_rel = rel_between(extract_root, root / "crates/z00z_crypto")
    storage_rel = rel_between(extract_root, root / "crates/z00z_storage")
    utils_rel = rel_between(extract_root, root / "crates/z00z_utils")
    wallets_rel = rel_between(extract_root, root / "crates/z00z_wallets")
    return textwrap.dedent(
        f"""\
        [package]
        name = "z00z-kani-fixture-extract"
        version = "0.1.0"
        edition = "2021"

        [workspace]

        [dependencies]
        serde_json = "1"
        z00z_core = {{ path = "{core_rel}", features = ["deterministic-rng"] }}
        z00z_crypto = {{ path = "{crypto_rel}" }}
        z00z_storage = {{ path = "{storage_rel}" }}
        z00z_utils = {{ path = "{utils_rel}", features = ["deterministic-rng"] }}
        z00z_wallets = {{ path = "{wallets_rel}" }}
        """
    )


def kani_fixture_extract_main_rs() -> str:
    return textwrap.dedent(
        """\
        use serde_json::json;
        use z00z_core::assets::{AssetClass, AssetPackPlain, AssetPackPlainMemo, AssetPkgWire, AssetWire};
        use z00z_crypto::expert::encoding::ByteArray;
        use z00z_crypto::expert::traits::DomainSeparation;
        use z00z_crypto::hash::hash_zk;
        use z00z_crypto::{frame_bytes, sign_kernel_signature, KernelSignature};
        use z00z_storage::checkpoint::{
            encode_art_bin, encode_draft_bin, encode_link_bin, CheckpointExecInputId, CheckpointId,
        };
        use z00z_storage::fixture_support::checkpoint_fixtures;
        use z00z_utils::rng::DeterministicRngProvider;
        use z00z_wallets::chain::ReceiverCardRecord;
        use z00z_wallets::core::key::{ReceiverKeys, ReceiverSecret};
        use z00z_wallets::core::receiver::{CardMetadata, PaymentRequest, ReceiverCard, RequestMetadata};
        use z00z_wallets::domains::IdentitySignatureDomain;
        use z00z_wallets::receiver::request::encode_request_compact;

        const REQUEST_SIGN_CTX: &[u8] = b"z00z.payment.request.v1";
        const CARD_SIGN_CTX: &[u8] = b"z00z.receiver.card.v1";

        fn signature_bytes(sig: &KernelSignature) -> [u8; 64] {
            let mut out = [0u8; 64];
            out[..32].copy_from_slice(sig.get_public_nonce().as_bytes());
            out[32..].copy_from_slice(sig.get_signature().as_bytes());
            out
        }

        fn identity_signature(
            message: &[u8],
            context: &[u8],
            identity_sk: &z00z_crypto::Z00ZScalar,
            seed: [u8; 32],
        ) -> [u8; 64] {
            let domain = hash_zk::<IdentitySignatureDomain>("IDENTITY_SIG", &[context, message]);
            let mut payload = frame_bytes(IdentitySignatureDomain::domain().as_bytes());
            payload.extend_from_slice(&frame_bytes(context));
            payload.extend_from_slice(&frame_bytes(message));
            payload.extend_from_slice(&frame_bytes(&domain));

            let mut rng = DeterministicRngProvider::from_seed(seed).rng();
            let sig = sign_kernel_signature(identity_sk, &payload, &mut rng).expect("sign");
            signature_bytes(&sig)
        }

        fn sample_keys(seed: [u8; 32]) -> ReceiverKeys {
            let secret = ReceiverSecret::from_bytes(seed).expect("receiver secret");
            ReceiverKeys::from_receiver_secret(secret).expect("receiver keys")
        }

        fn sample_request_compact() -> String {
            let keys = sample_keys([0x11; 32]);
            let mut request = PaymentRequest {
                version: 1,
                owner_handle: keys.owner_handle,
                view_pk: keys.view_pk.as_bytes().try_into().expect("view pk"),
                identity_pk: keys.identity_pk.as_bytes().try_into().expect("identity pk"),
                req_id: [0x22; 32],
                chain_id: 7,
                amount: Some(777),
                expiry: 4_102_444_800,
                metadata: Some(RequestMetadata {
                    memo: Some("fixture-request".to_string()),
                    payment_id: Some([0x33; 16]),
                    min_confirmations: Some(2),
                    return_receiver: Some("z00z:return:fixture".to_string()),
                    created_at: 1_735_689_600,
                }),
                signature: [0u8; 64],
            };
            let msg = request.canonical_encoding_unsigned();
            request.signature = identity_signature(
                &msg,
                REQUEST_SIGN_CTX,
                keys.reveal_identity_sk(),
                [0x44; 32],
            );
            encode_request_compact(&request)
        }

        fn sample_record_compact() -> String {
            let keys = sample_keys([0x51; 32]);
            let mut card = ReceiverCard {
                version: 1,
                owner_handle: keys.owner_handle,
                view_pk: keys.view_pk.as_bytes().try_into().expect("view pk"),
                identity_pk: keys.identity_pk.as_bytes().try_into().expect("identity pk"),
                card_id: Some([0x61; 16]),
                metadata: Some(CardMetadata {
                    created_at: 1_735_689_600,
                    display_name: Some("Verifier Receiver".to_string()),
                    valid_until: Some(4_102_444_800),
                    contact: Some("receiver@example.z00z".to_string()),
                }),
                signature: [0u8; 64],
            };
            let msg = card.canonical_encoding_unsigned();
            card.signature = identity_signature(&msg, CARD_SIGN_CTX, keys.reveal_identity_sk(), [0x62; 32]);
            let record = ReceiverCardRecord::new(&card, card.canonical_encoding(), 7).expect("record");
            record.to_compact().expect("compact")
        }

        fn main() {
            let artifact = encode_art_bin(&checkpoint_fixtures::artifact()).expect("artifact");
            let draft = encode_draft_bin(&checkpoint_fixtures::draft()).expect("draft");
            let link = encode_link_bin(&checkpoint_fixtures::link(
                CheckpointId::new([6u8; 32]),
                CheckpointExecInputId::new([8u8; 32]),
            ))
            .expect("link");

            let asset =
                z00z_core::genesis::asset_std::asset_from_dev_class(AssetClass::Coin, 1, 10).expect("asset");
            let dto = AssetPkgWire::from_wire(&AssetWire::from_asset(&asset));
            let asset_pkg_json = z00z_core::assets::encode_asset_pkg_json(&dto).expect("asset pkg");
            let asset_pack_basic = AssetPackPlain {
                value: 99,
                blinding: z00z_crypto::Z00ZScalar::one().to_bytes(),
                s_out: [0x22; 32],
            }
            .to_bytes();
            let asset_pack_memo = AssetPackPlainMemo {
                value: 99,
                blinding: z00z_crypto::Z00ZScalar::one().to_bytes(),
                s_out: [0x33; 32],
                memo: b"memo-lane".to_vec(),
            }
            .encode_checked()
            .expect("memo pack");

            let payload = json!({
                "sample_request_compact": sample_request_compact(),
                "sample_record_compact": sample_record_compact(),
                "checkpoint_artifact_bin": artifact,
                "checkpoint_draft_bin": draft,
                "checkpoint_link_bin": link,
                "asset_pkg_json": asset_pkg_json,
                "asset_pack_basic": asset_pack_basic,
                "asset_pack_memo": asset_pack_memo,
            });

            println!("{}", serde_json::to_string_pretty(&payload).expect("fixture json"));
        }
        """
    )


def extract_kani_fixture_payloads(root: Path, verification_root_rel: str) -> dict[str, object]:
    extract_root = (root / verification_root_rel / "_bootstrap" / "kani-fixture-extract").resolve()
    src_root = extract_root / "src"
    src_root.mkdir(parents=True, exist_ok=True)
    (extract_root / "Cargo.toml").write_text(
        kani_fixture_extract_cargo_toml(root, extract_root),
        encoding="utf-8",
    )
    (src_root / "main.rs").write_text(kani_fixture_extract_main_rs(), encoding="utf-8")

    env = os.environ.copy()
    env["CARGO_TARGET_DIR"] = str(extract_root / "target")
    result = subprocess.run(
        ["cargo", "run", "--quiet", "--release", "--manifest-path", str(extract_root / "Cargo.toml")],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
        env=env,
    )
    return json.loads(result.stdout)


def kani_wallet_compact_fixtures(payload: dict[str, object]) -> str:
    request = rust_string_literal(str(payload["sample_request_compact"]))
    record = rust_string_literal(str(payload["sample_record_compact"]))
    return textwrap.dedent(
        f"""\
        #![allow(unexpected_cfgs)]
        #![allow(dead_code)]
        #![cfg(kani)]

        // GENERATED BY z00z-verification-artifact-builder
        pub const SAMPLE_REQUEST_COMPACT: &str = {request};
        pub const SAMPLE_RECORD_COMPACT: &str = {record};
        """
    )


def kani_storage_checkpoint_fixtures(payload: dict[str, object]) -> str:
    artifact = rust_bytes_literal(list(payload["checkpoint_artifact_bin"]))
    draft = rust_bytes_literal(list(payload["checkpoint_draft_bin"]))
    link = rust_bytes_literal(list(payload["checkpoint_link_bin"]))
    return textwrap.dedent(
        f"""\
        #![allow(unexpected_cfgs)]
        #![allow(dead_code)]
        #![cfg(kani)]

        // GENERATED BY z00z-verification-artifact-builder
        pub const CHECKPOINT_ARTIFACT_BIN: &[u8] = &[
        {artifact}];
        pub const CHECKPOINT_DRAFT_BIN: &[u8] = &[
        {draft}];
        pub const CHECKPOINT_LINK_BIN: &[u8] = &[
        {link}];
        """
    )


def kani_core_asset_pkg_fixtures(payload: dict[str, object]) -> str:
    asset_pkg_json = rust_bytes_literal(list(payload["asset_pkg_json"]))
    asset_pack_basic = rust_bytes_literal(list(payload["asset_pack_basic"]))
    asset_pack_memo = rust_bytes_literal(list(payload["asset_pack_memo"]))
    return textwrap.dedent(
        f"""\
        #![allow(unexpected_cfgs)]
        #![allow(dead_code)]
        #![cfg(kani)]

        // GENERATED BY z00z-verification-artifact-builder
        pub const ASSET_PKG_JSON: &[u8] = &[
        {asset_pkg_json}];
        pub const ASSET_PACK_BASIC: &[u8] = &[
        {asset_pack_basic}];
        pub const ASSET_PACK_MEMO: &[u8] = &[
        {asset_pack_memo}];
        """
    )


def yaml_seq(items: list[str], fallback: str) -> list[str]:
    values = items or [fallback]
    return [f"    - {item}" for item in values]


def checkpoint_invariants(root: Path, specs_root_rel: str, fuzz_root_rel: str) -> str:
    rust_refs = files_with_terms(
        root,
        ["crates/z00z_storage/src", "crates/z00z_runtime/aggregators/src", "crates/z00z_runtime/watchers/src"],
        ["checkpoint", "root"],
        limit=8,
    )
    lines = [
        f"# {GEN_MARKER}",
        "CHECKPOINT-001:",
        "  statement: Every accepted checkpoint must preserve root lineage and must not consume the same input twice.",
        f"  tla: {specs_root_rel}/tla/Z00Z_Checkpoint.tla",
        "  rust:",
        *yaml_seq(rust_refs, "crates/z00z_storage/src/checkpoint/mod.rs"),
        "  kani:",
        "    - crates/z00z_storage/tests/generated_kani_checkpoint_artifact.rs",
        "  fuzz:",
        f"    - {fuzz_root_rel}/fuzz_targets/checkpoint_artifact_bin.rs",
        "  status: bootstrap-generated",
        "",
        "CHECKPOINT-002:",
        "  statement: Aggregator publication may only occur for already committed checkpoint state.",
        f"  tla: {specs_root_rel}/tla/Z00Z_Aggregator.tla",
        "  rust:",
        "    - crates/z00z_runtime/aggregators/src/recovery.rs",
        "    - crates/z00z_runtime/watchers/tests/test_hjmt_publication_contract.rs",
        "  status: bootstrap-generated",
    ]
    return "\n".join(lines) + "\n"


def asset_invariants(root: Path, specs_root_rel: str, fuzz_root_rel: str) -> str:
    rust_refs = files_with_terms(
        root,
        ["crates/z00z_core/src/assets", "crates/z00z_wallets/src", "crates/z00z_storage/src/settlement"],
        ["asset", "policy"],
        limit=8,
    )
    lines = [
        f"# {GEN_MARKER}",
        "ASSET-001:",
        "  statement: Rights and policy references must remain attached to a concrete asset lineage.",
        f"  alloy: {specs_root_rel}/alloy/z00z_asset_rights_voucher.als",
        "  rust:",
        *yaml_seq(rust_refs, "crates/z00z_core/src/assets/mod.rs"),
        "  kani:",
        "    - crates/z00z_core/tests/generated_kani_asset_pkg_json.rs",
        "  fuzz:",
        f"    - {fuzz_root_rel}/fuzz_targets/asset_pkg_json.rs",
        "  status: bootstrap-generated",
        "",
        "ASSET-002:",
        "  statement: Non-transferable rights must not become transferable through wrapper or voucher indirection.",
        f"  alloy: {specs_root_rel}/alloy/z00z_asset_rights_voucher.als",
        "  rust:",
        "    - crates/z00z_core/src/assets/right_config.rs",
        "    - crates/z00z_storage/src/settlement/hjmt_cache.rs",
        "  status: bootstrap-generated",
    ]
    return "\n".join(lines) + "\n"


def crypto_invariants(root: Path, specs_root_rel: str, fuzz_root_rel: str) -> str:
    rust_refs = files_with_terms(
        root,
        ["crates/z00z_wallets/src/receiver/request", "crates/z00z_wallets/src/chain", "crates/z00z_crypto/src", "crates/z00z_core/src/genesis"],
        ["proof"],
        limit=8,
    )
    lines = [
        f"# {GEN_MARKER}",
        "CRYPTO-001:",
        "  statement: Fiat-Shamir and request-signing contexts must stay domain-separated across proof and request families.",
        "  spec:",
        f"    - {specs_root_rel}/crypto/domain_separation_registry.yaml",
        f"    - {specs_root_rel}/crypto/transcript_binding.md",
        "  rust:",
        *yaml_seq(rust_refs, "crates/z00z_crypto/src/lib.rs"),
        "  status: bootstrap-generated",
        "",
        "CRYPTO-002:",
        "  statement: Payment request and receiver-card compact inputs must reject malformed or replayed compact payloads without panicking.",
        f"  tamarin: {specs_root_rel}/tamarin/z00z_payment_request.spthy",
        f"  proverif: {specs_root_rel}/proverif/z00z_payment_request_replay.pv",
        "  kani:",
        "    - crates/z00z_wallets/tests/generated_kani_payment_request_compact.rs",
        "    - crates/z00z_wallets/tests/generated_kani_receiver_card_record.rs",
        "  fuzz:",
        f"    - {fuzz_root_rel}/fuzz_targets/payment_request_compact.rs",
        f"    - {fuzz_root_rel}/fuzz_targets/receiver_card_record.rs",
        "  status: bootstrap-generated",
    ]
    return "\n".join(lines) + "\n"


def tla_checkpoint() -> str:
    return textwrap.dedent(
        f"""\
        ---- MODULE Z00Z_Checkpoint ----
        \\* {GEN_MARKER}
        EXTENDS FiniteSets, Naturals, TLC

        Inputs == 1..3
        Outputs == 11..13

        VARIABLES
          \\* @type: Set(Int);
          liveInputs,
          \\* @type: Set(Int);
          spentDelta,
          \\* @type: Set(Int);
          createdDelta,
          \\* @type: Bool;
          finalized

        TypeOK ==
          /\\ liveInputs \\subseteq Inputs
          /\\ spentDelta \\subseteq Inputs
          /\\ createdDelta \\subseteq Outputs
          /\\ finalized \\in BOOLEAN

        Init ==
          /\\ liveInputs = Inputs
          /\\ spentDelta = {{}}
          /\\ createdDelta = {{}}
          /\\ finalized = FALSE

        Propose ==
          \\E spend \\in SUBSET liveInputs:
            \\E create \\in SUBSET Outputs:
              /\\ spend # {{}}
              /\\ create # {{}}
              /\\ Cardinality(create) = Cardinality(spend)
              /\\ ~finalized
              /\\ spend \\cap spentDelta = {{}}
              /\\ create \\cap createdDelta = {{}}
              /\\ liveInputs' = liveInputs \\ spend
              /\\ spentDelta' = spentDelta \\cup spend
              /\\ createdDelta' = createdDelta \\cup create
              /\\ UNCHANGED finalized

        Finalize ==
          /\\ ~finalized
          /\\ Cardinality(spentDelta) = Cardinality(createdDelta)
          /\\ finalized' = TRUE
          /\\ UNCHANGED <<liveInputs, spentDelta, createdDelta>>

        Hold ==
          /\\ finalized
          /\\ UNCHANGED <<liveInputs, spentDelta, createdDelta, finalized>>

        \\* @type: () => <<Set(Int), Set(Int), Set(Int), Bool>>;
        CheckpointVars == <<liveInputs, spentDelta, createdDelta, finalized>>

        Next == Propose \\/ Finalize \\/ Hold

        NoDoubleSpend == spentDelta \\subseteq Inputs
        FinalizedSupplyBalanced ==
          finalized => Cardinality(spentDelta) = Cardinality(createdDelta)

        Spec == Init /\\ [][Next]_CheckpointVars
        ====
        """
    )


def tla_checkpoint_cfg() -> str:
    return textwrap.dedent(
        """\
        \\* GENERATED BY z00z-verification-artifact-builder
        SPECIFICATION Spec
        INVARIANT TypeOK
        INVARIANT NoDoubleSpend
        INVARIANT FinalizedSupplyBalanced

        """
    )


def tla_aggregator() -> str:
    return textwrap.dedent(
        f"""\
        ---- MODULE Z00Z_Aggregator ----
        \\* {GEN_MARKER}
        EXTENDS FiniteSets, Naturals

        BatchIds == 1..3

        VARIABLES
          \\* @type: Set(Int);
          pending,
          \\* @type: Set(Int);
          committed,
          \\* @type: Set(Int);
          published

        TypeOK ==
          /\\ pending \\subseteq BatchIds
          /\\ committed \\subseteq BatchIds
          /\\ published \\subseteq BatchIds

        Init ==
          /\\ pending = {{}}
          /\\ committed = {{}}
          /\\ published = {{}}

        Queue ==
          \\E b \\in BatchIds \\ (pending \\cup committed \\cup published):
            /\\ pending' = pending \\cup {{b}}
            /\\ UNCHANGED <<committed, published>>

        Commit ==
          \\E b \\in pending:
            /\\ pending' = pending \\ {{b}}
            /\\ committed' = committed \\cup {{b}}
            /\\ UNCHANGED published

        Publish ==
          \\E b \\in committed \\ published:
            /\\ published' = published \\cup {{b}}
            /\\ UNCHANGED <<pending, committed>>

        Done ==
          /\\ pending = {{}}
          /\\ published = committed
          /\\ UNCHANGED <<pending, committed, published>>

        \\* @type: () => <<Set(Int), Set(Int), Set(Int)>>;
        AggVars == <<pending, committed, published>>

        Next == Queue \\/ Commit \\/ Publish \\/ Done

        PublishRequiresCommit == published \\subseteq committed
        NoDuplicateLifecycle ==
          /\\ pending \\cap committed = {{}}
          /\\ pending \\cap published = {{}}

        Spec == Init /\\ [][Next]_AggVars
        ====
        """
    )


def tla_aggregator_cfg() -> str:
    return textwrap.dedent(
        """\
        \\* GENERATED BY z00z-verification-artifact-builder
        SPECIFICATION Spec
        INVARIANT TypeOK
        INVARIANT PublishRequiresCommit
        INVARIANT NoDuplicateLifecycle

        """
    )


def alloy_asset_model() -> str:
    return textwrap.dedent(
        f"""\
        // {GEN_MARKER}
        abstract sig TransferMode {{}}
        one sig Transferable, NonTransferable extends TransferMode {{}}

        abstract sig VoucherState {{}}
        one sig Fresh, Redeemed extends VoucherState {{}}

        sig Asset {{}}
        sig Policy {{}}

        sig Right {{
          asset: one Asset,
          policy: one Policy,
          mode: one TransferMode
        }}

        sig Voucher {{
          asset: one Asset,
          consumes: lone Right,
          state: one VoucherState
        }}

        sig Wrapper {{
          wraps: one Right,
          redeems: lone Voucher
        }}

        pred WellFormed {{
          all v: Voucher | some v.consumes implies v.consumes.asset = v.asset
          all w: Wrapper | some w.redeems implies w.redeems.asset = w.wraps.asset
        }}

        fun redeemedBy[v: Voucher]: set Wrapper {{
          redeems.v
        }}

        fact RedemptionDiscipline {{
          all v: Voucher | v.state = Redeemed iff one redeemedBy[v]
          all w: Wrapper | some w.redeems implies {{
            w.wraps.mode = Transferable
            w.redeems.state = Redeemed
            w.redeems.consumes = w.wraps
          }}
        }}

        assert NoVoucherDoubleRedeem {{
          WellFormed implies all disj w1, w2: Wrapper |
            some w1.redeems and w1.redeems = w2.redeems implies w1 = w2
        }}

        assert NonTransferableCannotMoveViaWrapper {{
          WellFormed implies all w: Wrapper |
            w.wraps.mode = NonTransferable implies no w.redeems
        }}

        assert VoucherCannotLoseAssetLineage {{
          WellFormed implies all v: Voucher | some v.consumes implies v.asset = v.consumes.asset
        }}

        check NoVoucherDoubleRedeem for 6
        check NonTransferableCannotMoveViaWrapper for 6
        check VoucherCannotLoseAssetLineage for 6
        """
    )


def domain_registry(domains: list[dict[str, str]]) -> str:
    lines = [
        f"# {GEN_MARKER}",
    ]
    for record in domains:
        lines.append(f"- name: {record['name']}")
        lines.append(f"  label: {record['label']}")
        lines.append(f"  version: {record['version']}")
        lines.append(f"  file: {record['file']}")
    return "\n".join(lines) + "\n"


def transcript_binding(root: Path) -> str:
    sources = files_with_terms(
        root,
        ["crates/z00z_wallets/src", "crates/z00z_storage/src", "crates/z00z_core/src", "crates/z00z_crypto/src"],
        ["proof"],
        limit=12,
    )
    source_lines = "\n".join(f"- `{item}`" for item in sources)
    return textwrap.dedent(
        f"""\
        <!-- {GEN_MARKER} -->
        # Z00Z Transcript Binding Bootstrap

        This bootstrap document records the minimum transcript fields that must be bound by Z00Z proof and compact-request families.

        ## Required Fields

        - `protocol_id`
        - `version`
        - `proof_type`
        - `domain`
        - `root`
        - `input`
        - `output`

        ## Proof Families

        ### checkpoint_artifact

        - protocol_id: `z00z.checkpoint`
        - version: `checkpoint artifact version`
        - proof_type: `checkpoint proof`
        - domain: `checkpoint root transition`
        - root: `prev_root -> next_root / claim_root`
        - input: `spent_delta`
        - output: `created_delta`

        ### payment_request

        - protocol_id: `z00z.payment.request`
        - version: `request version`
        - proof_type: `identity signature`
        - domain: `z00z.payment.request.v1`
        - root: `owner_handle / req_id binding root`
        - input: `view_pk + identity_pk + chain_id + amount + expiry`
        - output: `signed compact request`

        ### receiver_card_record

        - protocol_id: `z00z.receiver.card.record`
        - version: `record version`
        - proof_type: `card publication binding`
        - domain: `card_entry`
        - root: `registry_entry_id`
        - input: `receiver_card_bytes + card_epoch`
        - output: `verified compact record`

        ## Source Evidence

        {source_lines if source_lines else '- `crates/z00z_wallets/src/receiver/request/mod.rs`'}
        """
    )


def proof_objects_schema(root: Path) -> str:
    families = {
        "checkpoint_artifact": files_with_terms(root, ["crates/z00z_storage/src"], ["checkpoint", "proof"], 5),
        "payment_request": files_with_terms(root, ["crates/z00z_wallets/src/receiver/request"], ["request", "signature"], 5),
        "receiver_card_record": files_with_terms(root, ["crates/z00z_wallets/src/chain"], ["record", "card"], 5),
        "asset_package": files_with_terms(root, ["crates/z00z_core/src/assets"], ["asset", "decode"], 5),
    }
    lines = [f"# {GEN_MARKER}", "proof_objects:"]
    for name, sources in families.items():
        lines.append(f"  {name}:")
        lines.append("    binds:")
        for field in ("protocol_id", "version", "proof_type", "domain", "root", "input", "output"):
            lines.append(f"      - {field}")
        lines.append("    source_files:")
        if sources:
            for item in sources:
                lines.append(f"      - {item}")
        else:
            lines.append("      - unresolved")
    return "\n".join(lines) + "\n"


def model_coverage(root: Path, specs_root_rel: str, verification_root_rel: str) -> str:
    checkpoint_refs = files_with_terms(
        root,
        ["crates/z00z_storage/src", "crates/z00z_runtime/validators/src", "crates/z00z_runtime/aggregators/src"],
        ["checkpoint", "root"],
        8,
    )
    asset_refs = files_with_terms(
        root,
        ["crates/z00z_core/src", "crates/z00z_wallets/src", "crates/z00z_storage/src"],
        ["voucher", "rights"],
        8,
    )
    crypto_refs = files_with_terms(
        root,
        ["crates/z00z_crypto/src", "crates/z00z_wallets/src", "crates/z00z_storage/src"],
        ["proof"],
        8,
    )
    lines = [
        f"# {GEN_MARKER}",
        "models:",
        "  - id: checkpoint-lineage",
        "    level: l1",
        "    status_expectation: MODEL_CHECKED",
        "    tools:",
        f"      - tla: {specs_root_rel}/tla/Z00Z_Checkpoint.tla",
        f"      - apalache: {specs_root_rel}/tla/Z00Z_Checkpoint.tla",
        "    source_refs:",
        *yaml_seq(checkpoint_refs, "crates/z00z_storage/src/settlement/proof_batch.rs"),
        "  - id: asset-rights-voucher",
        "    level: l1",
        "    status_expectation: MODEL_CHECKED",
        "    tools:",
        f"      - alloy: {specs_root_rel}/alloy/z00z_asset_rights_voucher.als",
        "    source_refs:",
        *yaml_seq(asset_refs, "crates/z00z_core/src/assets/mod.rs"),
        "  - id: crypto-protocols",
        "    level: l2",
        "    status_expectation: SECURITY_PROTOCOL_PROVED",
        "    tools:",
        f"      - tamarin: {specs_root_rel}/tamarin/z00z_payment_request.spthy",
        f"      - tamarin: {specs_root_rel}/tamarin/z00z_stealth_delivery.spthy",
        f"      - proverif: {specs_root_rel}/proverif/z00z_payment_request_replay.pv",
        f"      - proverif: {specs_root_rel}/proverif/z00z_stealth_delivery.pv",
        "    source_refs:",
        *yaml_seq(crypto_refs, "crates/z00z_crypto/src/protocol/zkpack.rs"),
        "  - id: code-to-logic-bridge",
        "    level: l2",
        "    status_expectation: TESTED",
        "    tools:",
        f"      - refinement-map: {verification_root_rel}/code-to-logic/targets.yaml",
        f"      - cryptol: {specs_root_rel}/cryptol/serial_id.cry",
        f"      - cryptol: {specs_root_rel}/cryptol/zkpack_wire.cry",
        "    source_refs:",
        "    - crates/z00z_core/src/assets/serial_id.rs",
        "    - crates/z00z_crypto/src/protocol/zkpack.rs",
    ]
    return "\n".join(lines) + "\n"


def leakage_model(root: Path) -> str:
    wallet_refs = files_with_terms(root, ["crates/z00z_wallets/src"], ["stealth"], 8)
    zkpack_refs = files_with_terms(root, ["crates/z00z_crypto/src"], ["zkpack"], 8)
    payment_refs = files_with_terms(root, ["crates/z00z_wallets/src"], ["payment", "request"], 8)
    lines = [
        f"# {GEN_MARKER}",
        "claims:",
        "  - id: stealth-delivery-metadata",
        "    statement: Stealth delivery must not expose receiver identity beyond the chosen owner-tag and routing metadata contract.",
        "    source_refs:",
        *yaml_seq(wallet_refs, "crates/z00z_wallets/src/stealth/output/mod.rs"),
        "    allowed_public:",
        "      - protocol_version",
        "      - routing_class",
        "      - owner_tag_prefix",
        "    forbidden_public:",
        "      - receiver_secret_material",
        "      - decrypted_amount",
        "      - wallet_local_memo",
        "  - id: zkpack-wire-layout",
        "    statement: ZkPack wire format may expose only version byte, fixed ciphertext length, and fixed authentication tag geometry.",
        "    source_refs:",
        *yaml_seq(zkpack_refs, "crates/z00z_crypto/src/protocol/zkpack.rs"),
        "    allowed_public:",
        "      - version",
        "      - ciphertext_length",
        "      - tag_length",
        "    forbidden_public:",
        "      - plaintext_payload",
        "      - decrypted_fields",
        "  - id: compact-request-replay-surface",
        "    statement: Payment request compact forms must bind replay-relevant context rather than leak or reuse request identity across domains.",
        "    source_refs:",
        *yaml_seq(payment_refs, "crates/z00z_wallets/src/receiver/request/mod.rs"),
        "    allowed_public:",
        "      - request_version",
        "      - declared_chain_context",
        "    forbidden_public:",
        "      - reusable_signature_context",
        "      - secret_view_material",
    ]
    return "\n".join(lines) + "\n"


def tamarin_payment_request() -> str:
    return textwrap.dedent(
        f"""\
        theory z00z_payment_request begin

        /* {GEN_MARKER} */
        builtins: hashing

        functions: req/2

        rule Issue:
          [ Fr(~rid), Fr(~ctx) ]
          -->
          [ Request(~rid, ~ctx), Out(req(~rid, ~ctx)) ]

        rule Accept:
          [ Request(rid, ctx), In(req(rid, ctx)) ]
          -->
          [ Accepted(rid, ctx) ]

        lemma accept_implies_issue:
          "All rid ctx #i. Accepted(rid, ctx) @ i ==> Ex #j. Request(rid, ctx) @ j & #j < #i"

        lemma no_cross_context_replay:
          "All rid ctx1 ctx2 #i #j.
             Accepted(rid, ctx1) @ i
             & Accepted(rid, ctx2) @ j
             ==> ctx1 = ctx2"

        end
        """
    )


def tamarin_stealth_delivery() -> str:
    return textwrap.dedent(
        f"""\
        theory z00z_stealth_delivery begin

        /* {GEN_MARKER} */
        builtins: hashing

        functions: notice/3, owner_tag/2

        rule Send:
          [ Fr(~ephem), Fr(~payload) ]
          --[ Sent($receiver, ~payload, ~ephem) ]->
          [ !PendingDelivery($receiver, ~payload, ~ephem),
            Out(<owner_tag(~ephem, $receiver), notice(~payload, $receiver, ~ephem)>) ]

        rule Receive:
          [ !PendingDelivery($receiver, payload, ephem),
            In(<owner_tag(ephem, $receiver), notice(payload, $receiver, ephem)>) ]
          --[ Received($receiver, payload, ephem) ]->
          [ ]

        lemma receive_implies_send:
          "All receiver payload ephem #i.
             Received(receiver, payload, ephem) @ i
             ==> Ex #j. Sent(receiver, payload, ephem) @ j & #j < #i"

        end
        """
    )


def tamarin_inbox_notify() -> str:
    return textwrap.dedent(
        f"""\
        theory z00z_inbox_notify begin

        /* {GEN_MARKER} */
        builtins: hashing

        functions: notify/2

        rule Publish:
          [ Fr(~msg), Fr(~ctx) ]
          --[ Notice(~msg, ~ctx) ]->
          [ !Published(~msg, ~ctx), Out(notify(~msg, ~ctx)) ]

        rule Observe:
          [ !Published(msg, ctx), In(notify(msg, ctx)) ]
          --[ Observed(msg, ctx) ]->
          [ ]

        lemma observe_implies_publish:
          "All msg ctx #i. Observed(msg, ctx) @ i ==> Ex #j. Notice(msg, ctx) @ j & #j < #i"

        end
        """
    )


def proverif_payment_request() -> str:
    return textwrap.dedent(
        f"""\
        (* {GEN_MARKER} *)
        free c: channel.
        fun req(bitstring, bitstring): bitstring.

        event Issue(bitstring, bitstring).
        event Accept(bitstring, bitstring).

        query rid: bitstring, ctx: bitstring; event(Accept(rid, ctx)) ==> event(Issue(rid, ctx)).

        process
          new rid: bitstring;
          new ctx: bitstring;
          let r = req(rid, ctx) in
          event Issue(rid, ctx);
          out(c, r);
          in(c, x: bitstring);
          if x = r then event Accept(rid, ctx)
        """
    )


def proverif_stealth_delivery() -> str:
    return textwrap.dedent(
        f"""\
        (* {GEN_MARKER} *)
        free c: channel.
        fun notify(bitstring, bitstring): bitstring.

        event Sent(bitstring, bitstring).
        event Received(bitstring, bitstring).

        query payload: bitstring, receiver: bitstring;
          event(Received(payload, receiver)) ==> event(Sent(payload, receiver)).

        process
          new payload: bitstring;
          new receiver: bitstring;
          let msg = notify(payload, receiver) in
          event Sent(payload, receiver);
          out(c, msg);
          in(c, x: bitstring);
          if x = msg then event Received(payload, receiver)
        """
    )


def tamarin_voucher_acceptance() -> str:
    return textwrap.dedent(
        f"""\
        theory z00z_voucher_acceptance begin

        /* {GEN_MARKER} */
        builtins: hashing

        functions: voucher/2

        rule Issue:
          [ Fr(~vid), Fr(~asset) ]
          --[ Issued(~vid, ~asset) ]->
          [ Pending(~vid, ~asset), Out(voucher(~vid, ~asset)) ]

        rule Accept:
          [ Pending(vid, asset), In(voucher(vid, asset)) ]
          --[ Accepted(vid, asset) ]->
          [ AcceptedFact(vid, asset) ]

        rule Redeem:
          [ AcceptedFact(vid, asset) ]
          --[ Redeemed(vid, asset) ]->
          [ ]

        rule Refuse:
          [ Pending(vid, asset), In(voucher(vid, asset)) ]
          --[ Refused(vid, asset) ]->
          [ ]

        lemma redeem_implies_accept:
          "All vid asset #i. Redeemed(vid, asset) @ i ==> Ex #j. Accepted(vid, asset) @ j & #j < #i"

        lemma accept_implies_issue:
          "All vid asset #i. Accepted(vid, asset) @ i ==> Ex #j. Issued(vid, asset) @ j & #j < #i"

        lemma refusal_and_accept_cannot_both_happen:
          "All vid asset #i #j. Refused(vid, asset) @ i & Accepted(vid, asset) @ j ==> F"

        end
        """
    )


def proverif_voucher_acceptance() -> str:
    return textwrap.dedent(
        f"""\
        (* {GEN_MARKER} *)
        free c: channel.
        fun voucher(bitstring, bitstring): bitstring.

        event Issue(bitstring, bitstring).
        event Accept(bitstring, bitstring).
        event Redeem(bitstring, bitstring).

        query vid: bitstring, asset: bitstring; event(Accept(vid, asset)) ==> event(Issue(vid, asset)).
        query vid: bitstring, asset: bitstring; event(Redeem(vid, asset)) ==> event(Accept(vid, asset)).

        process
          new vid: bitstring;
          new asset: bitstring;
          let v = voucher(vid, asset) in
          event Issue(vid, asset);
          out(c, v);
          in(c, x: bitstring);
          if x = v then
            event Accept(vid, asset);
            event Redeem(vid, asset)
        """
    )


def kani_targets() -> str:
    return textwrap.dedent(
        f"""\
        # {GEN_MARKER}
        packages:
          - package: z00z_wallets
            harnesses:
              - crates/z00z_wallets/tests/generated_kani_payment_request_compact.rs
              - crates/z00z_wallets/tests/generated_kani_receiver_card_record.rs
          - package: z00z_storage
            harnesses:
              - crates/z00z_storage/tests/generated_kani_checkpoint_artifact.rs
          - package: z00z_core
            harnesses:
              - crates/z00z_core/tests/generated_kani_asset_pkg_json.rs
          - package: z00z_validators
            harnesses:
              - crates/z00z_runtime/validators/tests/generated_kani_validator_checkpoint_flow.rs
        """
    )


def verus_targets(verification_root_rel: str) -> str:
    return textwrap.dedent(
        f"""\
        # {GEN_MARKER}
        proofs:
          - file: {verification_root_rel}/verus/amount_arithmetic.rs
            claims:
              - amount arithmetic remains non-negative when spent does not exceed total
              - delta application preserves the original total when created equals spent
              - supply stays preserved when created equals spent
            source_refs:
              - crates/z00z_core/src/genesis/genesis_config_validate.rs
              - crates/z00z_storage/src/settlement/proof_batch.rs
          - file: {verification_root_rel}/verus/rights_transfer.rs
            claims:
              - non-transferable rights cannot redeem through wrapper indirection
              - redeemed vouchers are single-use
              - voucher redeem logic requires both transferability and an unreedeemed state
            source_refs:
              - crates/z00z_core/tests/assets/test_rights_config.rs
              - crates/z00z_storage/src/settlement/hjmt_cache.rs
          - file: {verification_root_rel}/verus/validator_determinism.rs
            claims:
              - validator acceptance implies every safety guard is true
              - any failed safety guard forces reject
            source_refs:
              - crates/z00z_runtime/validators/src/checkpoint.rs
              - crates/z00z_runtime/validators/tests/test_hjmt_publication_contract.rs
          - file: {verification_root_rel}/verus/transcript_domain.rs
            claims:
              - modeled transcript domains stay stable for a fixed version
              - changing the modeled version changes the domain identity
            source_refs:
              - crates/z00z_storage/src/settlement/proof_batch.rs
              - crates/z00z_wallets/src/stealth/tag.rs
        """
    )


def code_to_logic_generated_root(verification_root_rel: str) -> str:
    return f"{verification_root_rel}/code-to-logic/generated"


def code_to_logic_serial_id_manifest(verification_root_rel: str) -> str:
    return f"{code_to_logic_generated_root(verification_root_rel)}/serial_id_verify/Cargo.toml"


def code_to_logic_serial_id_lib(root: Path, verification_root_rel: str) -> str:
    crate_src_dir = root / code_to_logic_generated_root(verification_root_rel) / "serial_id_verify/src"
    serial_id_src = root / "crates/z00z_core/src/assets/serial_id.rs"
    serial_id_rel = rel_between(crate_src_dir, serial_id_src)
    return textwrap.dedent(
        f"""\
        #[path = "{serial_id_rel}"]
        pub mod serial_id;

        pub fn serial_roundtrip(value: u32) -> u32 {{
            serial_id::deserialize_serial_id(&serial_id::serialize_serial_id(value))
                .expect("serialize_serial_id always emits 4 bytes")
        }}

        pub fn serial_bounds_valid(value: u32, max: u32) -> bool {{
            serial_id::validate_serial_bounds(value, max).is_ok()
        }}

        #[cfg(crux)]
        #[allow(dead_code)]
        mod crux_test {{
            extern crate crucible;

            use super::*;
            use crucible::*;

            #[crux::test]
            fn serial_roundtrip_holds() {{
                let value = u32::symbolic("value");
                crucible_assert!(serial_roundtrip(value) == value);
            }}

            #[crux::test]
            fn serial_bounds_match_order() {{
                let value = u32::symbolic("value");
                let max = u32::symbolic("max");
                crucible_assert!(serial_bounds_valid(value, max) == (value < max));
            }}
        }}
        """
    )


def code_to_logic_serial_id_cargo_toml() -> str:
    return textwrap.dedent(
        """\
        [package]
        name = "z00z_code_to_logic_serial_id"
        version = "0.1.0"
        edition = "2021"

        [dependencies]
        thiserror = "2"

        [workspace]

        [lints.rust]
        unexpected_cfgs = { level = "allow", check-cfg = ['cfg(crux)'] }
        """
    )


def code_to_logic_serial_id_saw(verification_root_rel: str) -> str:
    json_rel = "../build/serial-id-roundtrip.linked-mir.json"
    _ = verification_root_rel
    return textwrap.dedent(
        f"""\
        m <- mir_load_module "{json_rel}";

        let serial_roundtrip_spec = do {{
          x <- mir_fresh_var "x" mir_u32;
          mir_execute_func [mir_term x];
          mir_return (mir_term x);
        }};

        mir_verify m "z00z_code_to_logic_serial_id::serial_roundtrip" [] false serial_roundtrip_spec z3;
        """
    )


def symbolic_u8_array(prefix: str, count: int, indent: str = "            ") -> str:
    return "\n".join(f'{indent}u8::symbolic("{prefix}{index:02d}"),' for index in range(count))


def code_to_logic_zkpack_manifest(verification_root_rel: str) -> str:
    return f"{code_to_logic_generated_root(verification_root_rel)}/zkpack_verify/Cargo.toml"


def code_to_logic_zkpack_lib(root: Path, verification_root_rel: str) -> str:
    crate_src_dir = root / code_to_logic_generated_root(verification_root_rel) / "zkpack_verify/src"
    zkpack_src = root / "crates/z00z_crypto/src/protocol/zkpack.rs"
    zkpack_rel = rel_between(crate_src_dir, zkpack_src)
    ciphertext_syms = symbolic_u8_array("ct", 72)
    tag_syms = symbolic_u8_array("tag", 16)
    return textwrap.dedent(
        f"""\
        #![allow(unexpected_cfgs)]

        #[path = "{zkpack_rel}"]
        pub mod zkpack;

        pub fn zkpack_roundtrip(
            ciphertext: [u8; zkpack::ZKPACK_CT_LEN],
            tag: [u8; zkpack::ZKPACK_TAG_LEN],
        ) -> bool {{
            let original = zkpack::ZkPackEncrypted {{
                version: zkpack::ZKPACK_VER,
                ciphertext: ciphertext.to_vec(),
                tag,
            }};
            match original.to_bytes() {{
                Ok(bytes) => match zkpack::ZkPackEncrypted::from_bytes(&bytes) {{
                    Ok(decoded) => decoded == original,
                    Err(_) => false,
                }},
                Err(_) => false,
            }}
        }}

        pub fn zkpack_rejects_bad_version(version: u8) -> bool {{
            let mut bytes = [0u8; zkpack::ZKPACK_TOTAL_LEN];
            bytes[0] = version;
            match zkpack::ZkPackEncrypted::from_bytes(&bytes) {{
                Ok(decoded) => version == zkpack::ZKPACK_VER && decoded.version == zkpack::ZKPACK_VER,
                Err(zkpack::ZkPackWireError::UnsupportedVersion) => version != zkpack::ZKPACK_VER,
                Err(_) => false,
            }}
        }}

        #[cfg(crux)]
        #[allow(dead_code)]
        mod crux_test {{
            extern crate crucible;

            use super::*;
            use crucible::*;

            #[crux::test]
            fn zkpack_roundtrip_holds() {{
                let ciphertext = [
        {ciphertext_syms}
                ];
                let tag = [
        {tag_syms}
                ];
                crucible_assert!(zkpack_roundtrip(ciphertext, tag));
            }}

            #[crux::test]
            fn zkpack_rejects_bad_version_holds() {{
                let version = u8::symbolic("version");
                crucible_assert!(zkpack_rejects_bad_version(version));
            }}
        }}
        """
    )


def code_to_logic_zkpack_build_rs() -> str:
    return textwrap.dedent(
        """\
        fn main() {
            println!("cargo:rustc-check-cfg=cfg(z00z_formal_no_serde)");
            println!("cargo:rustc-cfg=z00z_formal_no_serde");
        }
        """
    )


def code_to_logic_zkpack_cargo_toml() -> str:
    return textwrap.dedent(
        """\
        [package]
        name = "z00z_code_to_logic_zkpack"
        version = "0.1.0"
        edition = "2021"
        build = "build.rs"

        [dependencies]
        serde = { version = "1", features = ["derive"] }
        thiserror = "2"

        [workspace]

        [lints.rust]
        unexpected_cfgs = { level = "allow", check-cfg = ['cfg(crux)'] }
        """
    )


def code_to_logic_targets(specs_root_rel: str, verification_root_rel: str) -> str:
    serial_manifest = code_to_logic_serial_id_manifest(verification_root_rel)
    serial_saw = f"{verification_root_rel}/code-to-logic/saw/serial_id_roundtrip.saw"
    zkpack_manifest = code_to_logic_zkpack_manifest(verification_root_rel)
    return textwrap.dedent(
        f"""\
        # {GEN_MARKER}
        targets:
          - id: serial-id-roundtrip
            tool: saw
            manifest_path: {serial_manifest}
            saw_script: {serial_saw}
            required_status: FORMALLY_PROVED
            spec: {specs_root_rel}/cryptol/serial_id.cry
          - id: serial-id-symbolic
            tool: crux-mir
            manifest_path: {serial_manifest}
            required_status: BOUNDED_VERIFIED
            spec: {specs_root_rel}/cryptol/serial_id.cry
          - id: serial-id-llbc
            tool: charon-aeneas
            manifest_path: {serial_manifest}
            required_status: TESTED
            spec: {specs_root_rel}/cryptol/serial_id.cry
          - id: zkpack-symbolic
            tool: crux-mir
            manifest_path: {zkpack_manifest}
            required_status: BOUNDED_VERIFIED
            spec: {specs_root_rel}/cryptol/zkpack_wire.cry
          - id: zkpack-llbc
            tool: charon-aeneas
            manifest_path: {zkpack_manifest}
            required_status: TESTED
            spec: {specs_root_rel}/cryptol/zkpack_wire.cry
        """
    )


def cryptol_serial_id() -> str:
    return textwrap.dedent(
        f"""\
        // {GEN_MARKER}
        module Z00ZSerialId where

        // Bootstrap module for code-to-logic bridging.
        // The current executable gate checks that this Cryptol module parses and stays in sync
        // with the refinement map target that points at crates/z00z_core/src/assets/serial_id.rs.
        //
        // Next hardening step:
        //   - encode the exact little-endian byte layout
        //   - connect a SAW proof script for serialize/deserialize roundtrip
        """
    )


def cryptol_zkpack_wire() -> str:
    return textwrap.dedent(
        f"""\
        // {GEN_MARKER}
        module Z00ZZkPackWire where

        // Bootstrap module for the fixed-size ZkPack wire format in
        // crates/z00z_crypto/src/protocol/zkpack.rs.
        //
        // Next hardening step:
        //   - model the exact 1|72|16 byte layout
        //   - prove parser/serializer roundtrip and version rejection via SAW
        """
    )


def verus_amount_arithmetic() -> str:
    return textwrap.dedent(
        """\
        use vstd::prelude::*;

        verus! {

        spec fn apply_delta(total: nat, spent: nat, created: nat) -> int {
            total as int - spent as int + created as int
        }

        proof fn supply_preserved_when_spent_equals_created(total: nat, spent: nat, created: nat)
            requires
                spent <= total,
                spent == created,
            ensures
                apply_delta(total, spent, created) == total as int,
        {
        }

        proof fn delta_application_stays_non_negative(total: nat, spent: nat, created: nat)
            requires
                spent <= total,
            ensures
                apply_delta(total, spent, created) >= 0,
        {
        }

        } // verus!

        fn main() {}
        """
    )


def verus_rights_transfer() -> str:
    return textwrap.dedent(
        """\
        use vstd::prelude::*;

        verus! {

        spec fn redeem_allowed(is_transferable: bool, has_wrapper: bool, already_redeemed: bool) -> bool {
            is_transferable && has_wrapper && !already_redeemed
        }

        proof fn non_transferable_rights_never_redeem(has_wrapper: bool, already_redeemed: bool)
            ensures
                !redeem_allowed(false, has_wrapper, already_redeemed),
        {
        }

        proof fn redeemed_voucher_cannot_redeem_again(is_transferable: bool, has_wrapper: bool)
            ensures
                !redeem_allowed(is_transferable, has_wrapper, true),
        {
        }

        } // verus!

        fn main() {}
        """
    )


def verus_validator_determinism() -> str:
    return textwrap.dedent(
        """\
        use vstd::prelude::*;

        verus! {

        spec fn validator_accept(
            root_ok: bool,
            binding_ok: bool,
            replay_free: bool,
            proof_family_ok: bool,
        ) -> bool {
            root_ok && binding_ok && replay_free && proof_family_ok
        }

        proof fn accept_implies_all_guards(
            root_ok: bool,
            binding_ok: bool,
            replay_free: bool,
            proof_family_ok: bool,
        )
            ensures
                validator_accept(root_ok, binding_ok, replay_free, proof_family_ok)
                    ==> root_ok && binding_ok && replay_free && proof_family_ok,
        {
        }

        proof fn any_failed_guard_forces_reject(
            root_ok: bool,
            binding_ok: bool,
            replay_free: bool,
            proof_family_ok: bool,
        )
            ensures
                (!root_ok || !binding_ok || !replay_free || !proof_family_ok)
                    ==> !validator_accept(root_ok, binding_ok, replay_free, proof_family_ok),
        {
        }

        } // verus!

        fn main() {}
        """
    )


def verus_transcript_domain() -> str:
    return textwrap.dedent(
        """\
        use vstd::prelude::*;

        verus! {

        spec fn modeled_batch_domain(version: nat) -> (nat, nat) {
            (0x7a30307a, version)
        }

        proof fn same_version_keeps_modeled_domain(version: nat)
            ensures
                modeled_batch_domain(version) == modeled_batch_domain(version),
        {
        }

        proof fn changing_version_changes_modeled_domain(a: nat, b: nat)
            requires
                a != b,
            ensures
                modeled_batch_domain(a) != modeled_batch_domain(b),
        {
        }

        } // verus!

        fn main() {}
        """
    )


def hax_cargo_toml(root: Path, verification_root_rel: str) -> str:
    hax_root = root / verification_root_rel / "hax"
    crypto_rel = rel_between(hax_root, root / "crates/z00z_crypto")
    storage_rel = rel_between(hax_root, root / "crates/z00z_storage")
    return textwrap.dedent(
        f"""\
        # GENERATED BY z00z-verification-artifact-builder
        [package]
        name = "z00z_hax_surface"
        version = "0.0.0"
        edition = "2021"
        publish = false

        [workspace]
        members = ["."]

        [dependencies]
        z00z_crypto = {{ path = "{crypto_rel}" }}
        z00z_storage = {{ path = "{storage_rel}" }}
        """
    )


def hax_lib_rs() -> str:
    return textwrap.dedent(
        """\
        #![allow(dead_code)]

        pub fn model_owner_tag(owner_handle: [u8; 32], k_dh: [u8; 32]) -> [u8; 32] {
            z00z_crypto::compute_owner_tag(&owner_handle, &k_dh)
        }

        pub fn model_leaf_ad(
            asset_id: [u8; 32],
            serial_id: u32,
            r_pub: [u8; 32],
            owner_tag: [u8; 32],
            c_amount: [u8; 32],
        ) -> [u8; 32] {
            z00z_crypto::compute_leaf_ad(&asset_id, serial_id, &r_pub, &owner_tag, &c_amount)
        }

        pub fn model_batch_transcript_domain() -> [u8; 32] {
            z00z_storage::settlement::batch_proof_transcript_domain_v1()
        }
        """
    )


def hax_targets_json(verification_root_rel: str) -> str:
    return textwrap.dedent(
        f"""\
        {{
          "targets": [
            {{
              "name": "z00z_hax_surface_json",
              "manifest_path": "{verification_root_rel}/hax/Cargo.toml",
              "package": "z00z_hax_surface",
              "backend": "json",
              "output": "{verification_root_rel}/hax/out/z00z_hax_surface.json",
              "timeout_secs": 0
            }}
          ]
        }}
        """
    )


def fuzz_cargo_toml(root: Path, fuzz_root_rel: str) -> str:
    fuzz_root = root / fuzz_root_rel
    wallets_rel = rel_between(fuzz_root, root / "crates/z00z_wallets")
    storage_rel = rel_between(fuzz_root, root / "crates/z00z_storage")
    core_rel = rel_between(fuzz_root, root / "crates/z00z_core")
    return textwrap.dedent(
        f"""\
        # {GEN_MARKER}
        [package]
        name = "z00z-fuzz"
        version = "0.0.0"
        publish = false
        edition = "2021"

        [package.metadata]
        cargo-fuzz = true

        [workspace]
        members = ["."]

        [dependencies]
        libfuzzer-sys = "0.4"
        base64 = "0.22"
        z00z_wallets = {{ path = "{wallets_rel}" }}
        z00z_storage = {{ path = "{storage_rel}" }}
        z00z_core = {{ path = "{core_rel}" }}

        [[bin]]
        name = "payment_request_compact"
        path = "fuzz_targets/payment_request_compact.rs"
        test = false
        doc = false
        bench = false

        [[bin]]
        name = "receiver_card_record"
        path = "fuzz_targets/receiver_card_record.rs"
        test = false
        doc = false
        bench = false

        [[bin]]
        name = "checkpoint_artifact_bin"
        path = "fuzz_targets/checkpoint_artifact_bin.rs"
        test = false
        doc = false
        bench = false

        [[bin]]
        name = "asset_pkg_json"
        path = "fuzz_targets/asset_pkg_json.rs"
        test = false
        doc = false
        bench = false
        """
    )


def fuzz_gitignore() -> str:
    return textwrap.dedent(
        f"""\
        # {GEN_MARKER}
        artifacts
        corpus
        coverage
        target
        """
    )


def fuzz_payment_request() -> str:
    return textwrap.dedent(
        """\
        #![no_main]

        // GENERATED BY z00z-verification-artifact-builder
        use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
        use libfuzzer_sys::fuzz_target;

        fuzz_target!(|data: &[u8]| {
            let compact = URL_SAFE_NO_PAD.encode(data);
            let _ = z00z_wallets::receiver::request::decode_request_compact(&compact);
        });
        """
    )


def fuzz_receiver_card_record() -> str:
    return textwrap.dedent(
        """\
        #![no_main]

        // GENERATED BY z00z-verification-artifact-builder
        use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
        use libfuzzer_sys::fuzz_target;

        fuzz_target!(|data: &[u8]| {
            let compact = format!("z00zrc1:{}", URL_SAFE_NO_PAD.encode(data));
            let _ = z00z_wallets::chain::ReceiverCardRecord::from_compact(&compact, None);
        });
        """
    )


def fuzz_checkpoint_artifact_bin() -> str:
    return textwrap.dedent(
        """\
        #![no_main]

        // GENERATED BY z00z-verification-artifact-builder
        use libfuzzer_sys::fuzz_target;

        fuzz_target!(|data: &[u8]| {
            let _ = z00z_storage::checkpoint::decode_art_bin(data);
            let _ = z00z_storage::checkpoint::decode_draft_bin(data);
            let _ = z00z_storage::checkpoint::decode_link_bin(data);
            let _ = z00z_storage::checkpoint::decode_exec_bin(data);
        });
        """
    )


def fuzz_asset_pkg_json() -> str:
    return textwrap.dedent(
        """\
        #![no_main]

        // GENERATED BY z00z-verification-artifact-builder
        use libfuzzer_sys::fuzz_target;

        fuzz_target!(|data: &[u8]| {
            let _ = z00z_core::assets::decode_asset_pkg_json(data);
            let _ = z00z_core::assets::decode_asset_pack(
                data,
                z00z_core::assets::AssetPackVersion::Basic,
            );
            let _ = z00z_core::assets::decode_asset_pack(
                data,
                z00z_core::assets::AssetPackVersion::Memo,
            );
        });
        """
    )


def fuzz_core_asset_pack_from_bytes() -> str:
    return textwrap.dedent(
        """\
        #![no_main]

        // GENERATED BY z00z-verification-artifact-builder
        use libfuzzer_sys::fuzz_target;

        fuzz_target!(|data: &[u8]| {
            let _ = z00z_core::assets::decode_asset_pkg_json(data);
            let _ = z00z_core::assets::decode_asset_pack(
                data,
                z00z_core::assets::AssetPackVersion::Basic,
            );
            let _ = z00z_core::assets::decode_asset_pack(
                data,
                z00z_core::assets::AssetPackVersion::Memo,
            );
        });
        """
    )


def fuzz_crypto_from_bytes() -> str:
    return textwrap.dedent(
        """\
        #![no_main]

        // GENERATED BY z00z-verification-artifact-builder
        use libfuzzer_sys::fuzz_target;

        fuzz_target!(|data: &[u8]| {
            if data.len() >= 32 {
                let mut bytes = [0u8; 32];
                bytes.copy_from_slice(&data[..32]);
                let _ = z00z_crypto::Z00ZRistrettoPoint::try_from_bytes(bytes);
                let _ = z00z_crypto::Z00ZCompressedRistretto::try_from_bytes(bytes);
                let _ = z00z_crypto::Z00ZScalar::try_from_bytes(bytes);
            }
        });
        """
    )


def fuzz_crypto_take_32() -> str:
    return textwrap.dedent(
        """\
        #![no_main]

        // GENERATED BY z00z-verification-artifact-builder
        use libfuzzer_sys::fuzz_target;

        fuzz_target!(|data: &[u8]| {
            let _ = z00z_crypto::hashing::try_take_32(data);
            let _ = z00z_crypto::hashing::safe_take_32(data);
            let _ = z00z_crypto::hashing::take_32(data);
        });
        """
    )


def kani_wallet_payment_request() -> str:
    return textwrap.dedent(
        """\
        #![allow(unexpected_cfgs)]
        #![cfg(kani)]

        // GENERATED BY z00z-verification-artifact-builder
        #[path = "fixtures/generated_kani/compact.rs"]
        mod fixtures;

        #[kani::proof]
        fn generated_payment_request_compact_roundtrip_stable() {
            let decoded =
                z00z_wallets::receiver::request::decode_request_compact(fixtures::SAMPLE_REQUEST_COMPACT)
                    .expect("decode compact request");
            let reencoded = z00z_wallets::receiver::request::encode_request_compact(&decoded);
            assert_eq!(reencoded, fixtures::SAMPLE_REQUEST_COMPACT);
        }
        """
    )


def kani_wallet_receiver_card() -> str:
    return textwrap.dedent(
        """\
        #![allow(unexpected_cfgs)]
        #![cfg(kani)]

        // GENERATED BY z00z-verification-artifact-builder
        #[path = "fixtures/generated_kani/compact.rs"]
        mod fixtures;

        #[kani::proof]
        fn generated_receiver_card_record_roundtrip_stable() {
            let decoded = z00z_wallets::chain::ReceiverCardRecord::from_compact(
                fixtures::SAMPLE_RECORD_COMPACT,
                None,
            )
            .expect("decode compact receiver record");
            let reencoded = decoded.to_compact().expect("reencode compact receiver record");
            assert_eq!(reencoded, fixtures::SAMPLE_RECORD_COMPACT);
        }
        """
    )


def kani_storage_checkpoint() -> str:
    return textwrap.dedent(
        """\
        #![allow(unexpected_cfgs)]
        #![cfg(kani)]

        // GENERATED BY z00z-verification-artifact-builder
        #[kani::proof]
        fn generated_checkpoint_artifact_id_stable() {
            let artifact = z00z_storage::fixture_support::checkpoint_fixtures::artifact();
            let first = z00z_storage::checkpoint::derive_checkpoint_id(&artifact)
                .expect("derive checkpoint id");
            let second = z00z_storage::checkpoint::derive_checkpoint_id(&artifact)
                .expect("derive checkpoint id");
            assert_eq!(first, second);
        }

        #[kani::proof]
        fn generated_checkpoint_draft_id_stable() {
            let draft = z00z_storage::fixture_support::checkpoint_fixtures::draft();
            let first = z00z_storage::checkpoint::derive_draft_id(&draft)
                .expect("derive checkpoint draft id");
            let second = z00z_storage::checkpoint::derive_draft_id(&draft)
                .expect("derive checkpoint draft id");
            assert_eq!(first, second);
        }

        #[kani::proof]
        fn generated_checkpoint_exec_id_is_deterministic() {
            let first = z00z_storage::checkpoint::derive_exec_id(b"exec-input-v1");
            let second = z00z_storage::checkpoint::derive_exec_id(b"exec-input-v1");
            assert_eq!(first, second);
        }

        #[kani::proof]
        fn generated_checkpoint_exec_id_changes_with_input() {
            let first = z00z_storage::checkpoint::derive_exec_id(b"exec-input-v1");
            let second = z00z_storage::checkpoint::derive_exec_id(b"exec-input-v2");
            assert_ne!(first, second);
        }
        """
    )


def kani_core_asset_pkg() -> str:
    return textwrap.dedent(
        """\
        #![allow(unexpected_cfgs)]
        #![cfg(kani)]

        // GENERATED BY z00z-verification-artifact-builder
        #[path = "fixtures/generated_kani/asset_pkg.rs"]
        mod fixtures;

        #[kani::proof]
        fn generated_asset_pack_version_partition_is_total() {
            let serial: u32 = kani::any();
            let version = z00z_core::assets::validate_serial_id_version(serial);
            if serial <= 999_999 {
                assert_eq!(version, z00z_core::assets::AssetPackVersion::Basic);
            } else if serial <= 1_999_999 {
                assert_eq!(version, z00z_core::assets::AssetPackVersion::Memo);
            } else {
                assert_eq!(version, z00z_core::assets::AssetPackVersion::Unknown);
            }
        }

        #[kani::proof]
        fn generated_asset_pack_unknown_lane_rejects() {
            let err = z00z_core::assets::decode_asset_pack(
                &[0u8; 72],
                z00z_core::assets::AssetPackVersion::Unknown,
            )
            .expect_err("unknown lane must reject");
            assert_eq!(err, z00z_core::assets::PackErr::BadVer);
        }

        #[kani::proof]
        fn generated_asset_pack_basic_fixture_decodes() {
            let decoded = z00z_core::assets::decode_asset_pack(
                fixtures::ASSET_PACK_BASIC,
                z00z_core::assets::AssetPackVersion::Basic,
            )
            .expect("decode basic fixture");
            assert!(matches!(decoded, z00z_core::assets::DecodedAssetPack::Basic(_)));
        }
        """
    )


def kani_validator_checkpoint_flow() -> str:
    return textwrap.dedent(
        """\
        #![allow(unexpected_cfgs)]
        #![cfg(kani)]

        // GENERATED BY z00z-verification-artifact-builder
        use z00z_aggregators::{
            AggregatorId, BatchId, BatchRoute, ShardExecState, ShardExecTicket, ShardId,
            ShardPlacementView,
        };

        fn placement_view(shard_id: u16, generation: u64, aggregator_id: u16) -> ShardPlacementView {
            ShardPlacementView {
                route: BatchRoute {
                    shard_id: ShardId::new(shard_id),
                    routing_generation: generation,
                },
                primary_id: AggregatorId::new(aggregator_id),
                standby: Vec::new(),
                expected_journal_lineage: [0x61; 32],
            }
        }

        fn exec_ticket(
            batch_id: BatchId,
            shard_id: u16,
            generation: u64,
            aggregator_id: u16,
            state: ShardExecState,
        ) -> ShardExecTicket {
            ShardExecTicket {
                batch_id,
                placement: placement_view(shard_id, generation, aggregator_id),
                state,
            }
        }

        fn assert_placement_matches(
            placement: &ShardPlacementView,
            shard_id: u16,
            generation: u64,
            aggregator_id: u16,
        ) {
            assert_eq!(placement.route.shard_id, ShardId::new(shard_id));
            assert_eq!(placement.route.routing_generation, generation);
            assert_eq!(placement.primary_id, AggregatorId::new(aggregator_id));
            assert!(placement.standby.is_empty());
            assert_eq!(placement.expected_journal_lineage, [0x61; 32]);
        }

        fn assert_exec_matches(
            exec_ticket: &ShardExecTicket,
            batch_id: BatchId,
            shard_id: u16,
            generation: u64,
            aggregator_id: u16,
            state: ShardExecState,
        ) {
            assert_eq!(exec_ticket.batch_id, batch_id);
            assert_eq!(exec_ticket.state, state);
            assert_placement_matches(&exec_ticket.placement, shard_id, generation, aggregator_id);
        }

        #[kani::proof]
        fn generated_validator_runtime_prefers_exec_placement() {
            let batch_id = BatchId::from_bytes([0x31; 32]);
            let fallback = placement_view(1, 7, 3);
            let exec = exec_ticket(batch_id, 1, 7, 4, ShardExecState::Running);
            let runtime_placement =
                z00z_validators::kani_runtime_placement_parts(Some(&fallback), Some(&exec))
                    .expect("runtime placement");
            assert_placement_matches(runtime_placement, 1, 7, 4);

            let runtime_exec =
                z00z_validators::kani_runtime_exec_parts(Some(&exec)).expect("runtime exec");
            assert_exec_matches(runtime_exec, batch_id, 1, 7, 4, ShardExecState::Running);
        }

        #[kani::proof]
        fn generated_validator_runtime_falls_back_to_attached_placement() {
            let fallback = placement_view(1, 7, 3);
            let runtime_placement =
                z00z_validators::kani_runtime_placement_parts(Some(&fallback), None)
                    .expect("runtime placement");
            assert_placement_matches(runtime_placement, 1, 7, 3);
            assert!(z00z_validators::kani_runtime_exec_parts(None).is_none());
        }
        """
    )


def build_artifacts(
    root: Path,
    scope_kind: str,
    target_root_rel: str,
    specs_runtime_root: str | None,
    verification_runtime_root: str | None,
    fuzz_runtime_root: str | None,
    runtime_only: bool,
) -> dict:
    summary = {"created": [], "updated": [], "skipped": []}
    metadata = cargo_metadata(root)
    _ = metadata  # workspace existence validation
    domains = scan_domain_defs(root)
    report_stamp = os.environ.get("Z00Z_REPORT_TIMESTAMP") or datetime.now(
        timezone.utc
    ).strftime("%Y%m%d-%H%M%S")
    default_run_root_rel = canonical_run_root_rel(report_stamp)
    run_root_rel = normalize_runtime_root(
        root,
        os.environ.get("Z00Z_VERIFICATION_RUN_ROOT"),
        default_run_root_rel,
    )
    ensure_canonical_run_root_rel(run_root_rel)
    specs_root_rel = normalize_runtime_root(
        root, specs_runtime_root, f"{run_root_rel}/specs{report_stamp}"
    )
    verification_root_rel = normalize_runtime_root(
        root, verification_runtime_root, f"{run_root_rel}/verification{report_stamp}"
    )
    fuzz_root_rel = normalize_runtime_root(
        root, fuzz_runtime_root, f"{run_root_rel}/fuzz{report_stamp}"
    )
    ensure_report_local_runtime_root("specs runtime root", specs_root_rel, run_root_rel)
    ensure_report_local_runtime_root(
        "verification runtime root", verification_root_rel, run_root_rel
    )
    ensure_report_local_runtime_root("fuzz runtime root", fuzz_root_rel, run_root_rel)

    want_checkpoint = scope_kind == "project" or target_root_rel.startswith(
        (
            "crates/z00z_storage",
            "crates/z00z_runtime/aggregators",
            "crates/z00z_runtime/validators",
            "crates/z00z_runtime/watchers",
        )
    )
    want_assets = scope_kind == "project" or target_root_rel.startswith(("crates/z00z_core", "crates/z00z_wallets"))
    want_crypto = scope_kind == "project" or target_root_rel.startswith(("crates/z00z_wallets", "crates/z00z_crypto", "crates/z00z_core"))
    want_exec = scope_kind == "project" or target_root_rel.startswith(
        (
            "crates/z00z_wallets",
            "crates/z00z_storage",
            "crates/z00z_core",
            "crates/z00z_crypto",
            "crates/z00z_runtime/validators",
        )
    )
    want_security_review = scope_kind == "project" or target_root_rel.startswith(
        (
            "crates/z00z_wallets",
            "crates/z00z_storage",
            "crates/z00z_core",
            "crates/z00z_crypto",
            "crates/z00z_runtime/validators",
            "crates/z00z_networks_rpc",
        )
    )

    if want_checkpoint:
        manual_or_owned_write(root, f"{specs_root_rel}/invariants/checkpoint_invariants.yaml", checkpoint_invariants(root, specs_root_rel, fuzz_root_rel), summary, "invariants")
        manual_or_owned_write(root, f"{specs_root_rel}/tla/Z00Z_Checkpoint.tla", tla_checkpoint(), summary, "tla")
        manual_or_owned_write(root, f"{specs_root_rel}/tla/Z00Z_Checkpoint.cfg", tla_checkpoint_cfg(), summary, "tla")
        manual_or_owned_write(root, f"{specs_root_rel}/tla/Z00Z_Aggregator.tla", tla_aggregator(), summary, "tla")
        manual_or_owned_write(root, f"{specs_root_rel}/tla/Z00Z_Aggregator.cfg", tla_aggregator_cfg(), summary, "tla")

    if want_assets:
        manual_or_owned_write(root, f"{specs_root_rel}/invariants/assets_rights_policy_invariants.yaml", asset_invariants(root, specs_root_rel, fuzz_root_rel), summary, "invariants")
        manual_or_owned_write(root, f"{specs_root_rel}/alloy/z00z_asset_rights_voucher.als", alloy_asset_model(), summary, "alloy")

    if want_crypto:
        manual_or_owned_write(root, f"{specs_root_rel}/invariants/crypto_invariants.yaml", crypto_invariants(root, specs_root_rel, fuzz_root_rel), summary, "invariants")
        manual_or_owned_write(root, f"{specs_root_rel}/crypto/domain_separation_registry.yaml", domain_registry(domains), summary, "crypto-spec")
        manual_or_owned_write(root, f"{specs_root_rel}/crypto/transcript_binding.md", transcript_binding(root), summary, "crypto-spec")
        manual_or_owned_write(root, f"{specs_root_rel}/crypto/proof_objects_schema.yaml", proof_objects_schema(root), summary, "crypto-spec")
        manual_or_owned_write(root, f"{specs_root_rel}/crypto/leakage_model.yaml", leakage_model(root), summary, "crypto-spec")
        manual_or_owned_write(root, f"{specs_root_rel}/tamarin/z00z_payment_request.spthy", tamarin_payment_request(), summary, "tamarin")
        manual_or_owned_write(root, f"{specs_root_rel}/tamarin/z00z_stealth_delivery.spthy", tamarin_stealth_delivery(), summary, "tamarin")
        manual_or_owned_write(root, f"{specs_root_rel}/tamarin/z00z_inbox_notify.spthy", tamarin_inbox_notify(), summary, "tamarin")
        manual_or_owned_write(root, f"{specs_root_rel}/tamarin/z00z_voucher_acceptance.spthy", tamarin_voucher_acceptance(), summary, "tamarin")
        manual_or_owned_write(root, f"{specs_root_rel}/proverif/z00z_payment_request_replay.pv", proverif_payment_request(), summary, "proverif")
        manual_or_owned_write(root, f"{specs_root_rel}/proverif/z00z_stealth_delivery.pv", proverif_stealth_delivery(), summary, "proverif")
        manual_or_owned_write(root, f"{specs_root_rel}/proverif/z00z_voucher_acceptance.pv", proverif_voucher_acceptance(), summary, "proverif")

    if want_security_review:
        manual_or_owned_write(root, f"{verification_root_rel}/security/prompt_corpus.json", security_prompt_corpus(root), summary, "security")
        manual_or_owned_write(root, f"{verification_root_rel}/security/attack_surface_registry.json", attack_surface_registry(root, scope_kind, target_root_rel, verification_root_rel), summary, "security")

    if want_exec:
        manual_or_owned_write(root, f"{verification_root_rel}/kani/targets.yaml", kani_targets(), summary, "verification")
        manual_or_owned_write(root, f"{verification_root_rel}/verus/targets.yaml", verus_targets(verification_root_rel), summary, "verification")
        manual_or_owned_write(root, f"{verification_root_rel}/verus/amount_arithmetic.rs", verus_amount_arithmetic(), summary, "verification")
        manual_or_owned_write(root, f"{verification_root_rel}/verus/rights_transfer.rs", verus_rights_transfer(), summary, "verification")
        manual_or_owned_write(root, f"{verification_root_rel}/verus/validator_determinism.rs", verus_validator_determinism(), summary, "verification")
        manual_or_owned_write(root, f"{verification_root_rel}/verus/transcript_domain.rs", verus_transcript_domain(), summary, "verification")
        manual_or_owned_write(root, f"{verification_root_rel}/model_coverage.yaml", model_coverage(root, specs_root_rel, verification_root_rel), summary, "verification")
        manual_or_owned_write(root, f"{verification_root_rel}/code-to-logic/targets.yaml", code_to_logic_targets(specs_root_rel, verification_root_rel), summary, "verification")
        manual_or_owned_write(root, code_to_logic_serial_id_manifest(verification_root_rel), code_to_logic_serial_id_cargo_toml(), summary, "verification")
        manual_or_owned_write(root, f"{code_to_logic_generated_root(verification_root_rel)}/serial_id_verify/src/lib.rs", code_to_logic_serial_id_lib(root, verification_root_rel), summary, "verification")
        manual_or_owned_write(root, f"{verification_root_rel}/code-to-logic/saw/serial_id_roundtrip.saw", code_to_logic_serial_id_saw(verification_root_rel), summary, "verification")
        manual_or_owned_write(root, code_to_logic_zkpack_manifest(verification_root_rel), code_to_logic_zkpack_cargo_toml(), summary, "verification")
        manual_or_owned_write(root, f"{code_to_logic_generated_root(verification_root_rel)}/zkpack_verify/build.rs", code_to_logic_zkpack_build_rs(), summary, "verification")
        manual_or_owned_write(root, f"{code_to_logic_generated_root(verification_root_rel)}/zkpack_verify/src/lib.rs", code_to_logic_zkpack_lib(root, verification_root_rel), summary, "verification")
        manual_or_owned_write(root, f"{specs_root_rel}/cryptol/serial_id.cry", cryptol_serial_id(), summary, "verification")
        manual_or_owned_write(root, f"{specs_root_rel}/cryptol/zkpack_wire.cry", cryptol_zkpack_wire(), summary, "verification")
        manual_or_owned_write(root, f"{verification_root_rel}/hax/Cargo.toml", hax_cargo_toml(root, verification_root_rel), summary, "verification")
        manual_or_owned_write(root, f"{verification_root_rel}/hax/src/lib.rs", hax_lib_rs(), summary, "verification")
        manual_or_owned_write(root, f"{verification_root_rel}/hax/targets.json", hax_targets_json(verification_root_rel), summary, "verification")
        manual_or_owned_write(root, f"{fuzz_root_rel}/Cargo.toml", fuzz_cargo_toml(root, fuzz_root_rel), summary, "fuzz")
        manual_or_owned_write(root, f"{fuzz_root_rel}/.gitignore", fuzz_gitignore(), summary, "fuzz")
        manual_or_owned_write(root, f"{fuzz_root_rel}/fuzz_targets/payment_request_compact.rs", fuzz_payment_request(), summary, "fuzz-target")
        manual_or_owned_write(root, f"{fuzz_root_rel}/fuzz_targets/receiver_card_record.rs", fuzz_receiver_card_record(), summary, "fuzz-target")
        manual_or_owned_write(root, f"{fuzz_root_rel}/fuzz_targets/checkpoint_artifact_bin.rs", fuzz_checkpoint_artifact_bin(), summary, "fuzz-target")
        manual_or_owned_write(root, f"{fuzz_root_rel}/fuzz_targets/asset_pkg_json.rs", fuzz_asset_pkg_json(), summary, "fuzz-target")
        if runtime_only:
            return summary
        kani_fixtures = extract_kani_fixture_payloads(root, verification_root_rel)
        manual_or_owned_write(root, "crates/z00z_core/fuzz/fuzz_targets/fuzz_target_asset_pack_from_bytes.rs", fuzz_core_asset_pack_from_bytes(), summary, "fuzz-target")
        manual_or_owned_write(root, "crates/z00z_crypto/fuzz/fuzz_targets/fuzz_from_bytes.rs", fuzz_crypto_from_bytes(), summary, "fuzz-target")
        manual_or_owned_write(root, "crates/z00z_crypto/fuzz/fuzz_targets/fuzz_take_32.rs", fuzz_crypto_take_32(), summary, "fuzz-target")
        manual_or_owned_write(root, "crates/z00z_wallets/tests/fixtures/generated_kani/compact.rs", kani_wallet_compact_fixtures(kani_fixtures), summary, "kani-fixture")
        manual_or_owned_write(root, "crates/z00z_storage/tests/fixtures/generated_kani/checkpoint.rs", kani_storage_checkpoint_fixtures(kani_fixtures), summary, "kani-fixture")
        manual_or_owned_write(root, "crates/z00z_core/tests/fixtures/generated_kani/asset_pkg.rs", kani_core_asset_pkg_fixtures(kani_fixtures), summary, "kani-fixture")
        manual_or_owned_write(root, "crates/z00z_wallets/tests/generated_kani_payment_request_compact.rs", kani_wallet_payment_request(), summary, "kani-harness")
        manual_or_owned_write(root, "crates/z00z_wallets/tests/generated_kani_receiver_card_record.rs", kani_wallet_receiver_card(), summary, "kani-harness")
        manual_or_owned_write(root, "crates/z00z_storage/tests/generated_kani_checkpoint_artifact.rs", kani_storage_checkpoint(), summary, "kani-harness")
        manual_or_owned_write(root, "crates/z00z_core/tests/generated_kani_asset_pkg_json.rs", kani_core_asset_pkg(), summary, "kani-harness")
        manual_or_owned_write(root, "crates/z00z_runtime/validators/tests/generated_kani_validator_checkpoint_flow.rs", kani_validator_checkpoint_flow(), summary, "kani-harness")

    return summary


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", required=True)
    parser.add_argument("--scope-kind", required=True, choices=["project", "crate"])
    parser.add_argument("--target-root-rel", default="")
    parser.add_argument("--summary-out")
    parser.add_argument("--specs-runtime-root")
    parser.add_argument("--verification-runtime-root")
    parser.add_argument("--fuzz-runtime-root")
    parser.add_argument("--runtime-only", action="store_true")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    summary = build_artifacts(
        root,
        args.scope_kind,
        args.target_root_rel,
        args.specs_runtime_root,
        args.verification_runtime_root,
        args.fuzz_runtime_root,
        args.runtime_only,
    )

    if args.summary_out:
        out_path = Path(args.summary_out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    else:
        print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
