#!/usr/bin/env bash
# bootstrap_tests.sh — fast-fail subset generated by smart-tests-bootstrap
# Codebase snapshot: 2026-03-27 | Total tests: ~3373 | Selected: ~850 (~25%)
# Breakdown: foundational lib (766) + wallet integration (84) + benches/examples compile
# Physical path: ./.github/skills/smart-tests-bootstrap/scripts/bootstrap_tests.sh
set -euo pipefail

THREADS="${BOOTSTRAP_THREADS:-4}"

build_examples_if_present() {
  local crate="$1"
  local feature_args="${2:-}"
  local dir="crates/$crate/examples"
  if [ -d "$dir" ] && find "$dir" -maxdepth 1 -type f -print -quit | grep -q .; then
    cargo build -p "$crate" --examples --release $feature_args 2>&1 | tail -3
  else
    echo "skip $crate examples: no example targets"
  fi
}

echo "=== foundational units ==="
cargo test -p z00z_crypto   --release --features test-params-fast --lib -- --test-threads "$THREADS"
cargo test -p z00z_core     --release --features test-params-fast --lib -- --test-threads "$THREADS"
cargo test -p z00z_storage  --release --features test-params-fast --lib -- --test-threads "$THREADS"
cargo test -p z00z_utils    --release --features test-params-fast --lib -- --test-threads "$THREADS"

echo "=== wallet integration ==="
cargo test -p z00z_wallets --release --features claim-auth-sign \
  --test test_tx_stealth_flow \
  --test test_tx_tamper \
  --test test_tx_fee \
  --test test_tx_roundtrip \
  --test test_tx_poison \
  --test test_tx_balance \
  --test test_golden_vectors \
  --test test_golden_tag16 \
  --test test_golden_recv_keys \
  --test test_golden_owner_tag \
  --test test_manager \
  --test test_manager_storage_unlock \
  --test test_ecdh \
  --test test_kdf \
  --test test_adversarial \
  --test test_claim_core_safety \
  --test test_claim_import_reason_codes \
  --test test_claim_resume_core \
  --test test_claim_state_compat \
  --test test_claim_state_core \
  --test test_asset_replay_protection \
  --test test_asset_ownership_security \
  -- --test-threads "$THREADS"

echo "=== compile checks ==="
cargo bench -p z00z_crypto  --no-run --features test-params-fast 2>&1 | tail -3
cargo bench -p z00z_core    --no-run --features test-params-fast 2>&1 | tail -3
cargo bench -p z00z_storage --no-run --features test-params-fast 2>&1 | tail -3
cargo bench -p z00z_wallets --no-run 2>&1 | tail -3
build_examples_if_present z00z_crypto "--features test-params-fast"
build_examples_if_present z00z_wallets

echo "=== BOOTSTRAP COMPLETE ==="
